### ISSUE TITLE
Question: Does CNI support multi-hosts network

### ISSUE THREAD

**Issue by ghost** [containernetworking/cni#106]
Hi,

Can you please let me know if CNI currently support multi-host (overlay) network so that containers in different hosts can communicate in the same network? Thanks!

**Comment by steveeJ** [comment]
@zhq527725 CNI currently supports this via the [flannel plugin](https://github.com/appc/cni/blob/master/Documentation/flannel.md). If you give it a try we'd be happy to receive any feedback.

**Comment by zhq527725** [comment]
Great! I'd love to have a try and let you know for any feedbacks, thanks @steveeJ!
