### ISSUE TITLE
[Proposal] - Add host-local IPAM support for IPv4 and IPv6 at same time

### ISSUE THREAD

**Issue by aanm** [containernetworking/cni#111]
Currently the host-local IPAM doesn't allow to have a pool of IPv4 and IPv6 addresses.
Does it make sense to have that?

**Comment by steveeJ** [comment]
This would make a lot of sense and I've been thinking how to allow this without breaking compatibility and still keep it simple. @squaremo any great ideas?

**Comment by qianzhangxa** [comment]
@aanm and @steveeJ, can you please clarify the behavior of `host-local` IPAM plugin supporting IPv4 and IPv6 at the same time. Does that mean after calling `host-local` IPAM plugin the caller will get two IPs (one IPv4 and one IPv6)? But I think the caller will only pass one interface name (e.g., eth0) to the plugin via CNI_IFNAME, so if there are two IPs allocated, we will set both of them up on that single interface?

And what about `dhcp` IPAM plugin? Will it support IPv4 and IPv6 as the same time too?

**Comment by aanm** [comment]
@qianzhangxa In my opinion, yes for all the questions. Unless we could change the caller request to have an option like that would allow him to specify which kind of IP (IPv4: true, IPv6: true) wants to that interface.

**Comment by bboreham** [comment]
Fixed in https://github.com/containernetworking/plugins/pull/12
