### ISSUE TITLE
IPAM allocator and backend should be decoupled

### ISSUE THREAD

**Issue by steveeJ** [containernetworking/cni#116]
We could reorganize the current implementation which could be done right now without losing compatibility with existing configurations.
- ipam
  - host-local.go (implements combination of disk and sequential)
  - store
    - store.go (package, interface)
    - disk/...
  - allocator
    - allocator.go (package, interface)
    - sequential/...

However, the next step could be to configure the store and allocator in the configuration file, so that any combination could be chosen. We can probably still allow predefined combinations for known types as _host-local_.

/cc @aanm

**Comment by aanm** [comment]
Answering to the #115 question, I'm currently using the `IPAMConfig struct` and the allocator on a different IPAM.

**Comment by jonboulle** [comment]
Splitting this apart SGTM
