### ISSUE TITLE
Question: Can any CNI main plugins work with any CNI IPAM plugins?

### ISSUE THREAD

**Issue by qianzhangxa** [containernetworking/cni#122]
I'd like to know if there is any restriction about which main plugin can work with which IPAM plugin? E.g., Can bridge and ptp plugin work with dhcp plugin? Or they have to work with host-local plugin? Can macvlan plugin work with host-local plugin? Or it has to work with dhcp plugin?

**Comment by steveeJ** [comment]
I'll go into some of your examples in a bit, upfront there are certain restrictions which stem from the nature of the interface types and how they are used in these plugins.

* ptp: we use veth devices to create point-to-point connections between two network namespaces. DHCP won't work out of the box with this, as it needs layer 2 connectivity to the a network the DHCP server listening on. Technically you could combine PTP and DHCP plugins but it doesn't make much sense as it wasn't design like that in CNI.
* bridge: bridge is more likely to work with DHCP, but you still have to go through the extra effort and either run a DHCP server on the interface directly, or attach an interface to the bridge that has layer 2 connectivity to a DHCP server.
* macvlan: this can work out of the box with DHCP if you provide a master interface that again has layer 2 connectivity to a DHCP server, but it will also work with host-local if you configure the range to be one of the master interface's network addresses that doesn't conflict with an existing DHCP range

I suggest that you take a look at the CNI docs, the code and also the kernel's documentation on the specific drivers. If there's any chance I would like to encourage you to extend CNI's documentation anywhere in the repository with information that is useful for all people getting started with CNI. Simply put, pleas write up what you learned and create a pull request to include it in our docs :-)

**Comment by steveeJ** [comment]
@qianzhangxa is the issue resolved for you or do you have any other questions?

**Comment by leodotcloud** [comment]
@qianzhangxa If your question has been answered, could you please close the issue? Otherwise further discussions/comments/questions are really welcome.
