### ISSUE TITLE
README: various improvements

### ISSUE THREAD

**Issue by jonboulle** [containernetworking/cni#125]
- [x] describe current state of project and roadmap/timeline 
- [x] link to implementations/integrations (e.g. rkt, kubernetes, calico, weave)
- [x] encourage people to get involved and describe how
- [x] Roadmap https://github.com/coreos/rkt/blob/master/ROADMAP.md #218

**Comment by squaremo** [comment]
Also worth considering:

 * contribution guidelines (commit messages e.g.)
 * how planning/roadmaps works

**Comment by jonboulle** [comment]
FWIW, there is a contribution guide [here](https://github.com/appc/cni/blob/master/CONTRIBUTING.md). That document is just a fork of our standard CoreOS one, feel free to tweak/simplify/fold into README as desired.

**Comment by steveeJ** [comment]
@squaremo any updates on this one?

**Comment by squaremo** [comment]
> any updates on this one?

Working on it in my spare time :)

**Comment by jonboulle** [comment]
I suggest punting so we can release a 0.2.0 asap.

**Comment by squaremo** [comment]
OK, let me put some uncontroversial changes into a PR quickly ..

**Comment by steveeJ** [comment]
@jonboulle 

> encourage people to get involved and describe how

Is https://github.com/appc/cni#contributing-to-cni enough to check that box?

**Comment by steveeJ** [comment]
Last bits fixed by #218.
