### ISSUE TITLE
Increasing CNI's scope?

### ISSUE THREAD

**Issue by steveeJ** [containernetworking/cni#147]
While the single plugins are independent (well, not really, e.g. (meta<->)main<->ipam), wouldn't CNI actually benefit of a holistic view on the situation? Without that, there will always be the need for consumers to put workarounds in place and go back and forth to retrieve information that will be used for the next invocation. I would prefer to pass a netns and multiple network configuration files to CNI **at once**, then receive one merged result back. 

This would also allow for functionality that is currently at the consumer's level or are not really possible at this point at all:
- error-catching like detecting same-metric duplicated default routes, conflicting subnets, etc.
- primary interface determination
- if port forwarding/inter-pod communication is introduced in CNI, detect conflicting rules from the declarations alone

Practically, this could happen without changing the spec too much by having a meta plugin that handles execution of all plugins that are referenced by the passed in configuration file**s**.

**Comment by squaremo** [comment]
If we're thinking of having CNI take on some responsibility for e.g., providing interface names, it makes sense to go on and have the convenience of bulk operations.

There would have to be some thought put into what to do with partial failures -- either transactional behaviour (probably impossible) or at least the ability to roll back and try again.

Could this be done as a broadening of the libcni API (i.e., available primarily to applications using CNI, including the `cnitool`), rather than a meta plugin, which is the responsibility of the operator to configure?

**Comment by jonboulle** [comment]
> Practically, this could happen without changing the spec too much by having a meta plugin that handles execution of all plugins that are referenced by the passed in configuration files.

if you go this route, what needs to change here at all?

**Comment by steveeJ** [comment]
>> Practically, this could happen without changing the spec too much by having a meta plugin that handles execution of all plugins that are referenced by the passed in configuration files.
> 
> if you go this route, what needs to change here at all?
Heading in the direction of #145, the result information will be more complex. I imagine this to be flexible enough to have dynamic type result containing list of embedded results from the different network configuration files. This requires the result specification to be adapted.

**Comment by steveeJ** [comment]
@squaremo
> Could this be done as a broadening of the libcni API (i.e., available primarily to applications using CNI, including the cnitool), rather than a meta plugin, which is the responsibility of the operator to configure?
Yes, I think the problem could be solved by extending libcni. Let's think that approach through, it'll allow us to be more experimental before we settle the features, and we always have the possibility to merge it into the specification if we like it a lot ;-)

I'd like to collect suggestions how to describe the compatibility between plugins, I'm looking for something declarative, so definitely not just plain English. Starting with a probably incomplete list of what we need express to handle plugins, their combinations and cooperation gracefully:
* Generic coexistence incompatibility, e.g. ipvlan and macvlan
* Main/Meta/IPAM compatibility
* CNI_ARGS options per plugin

Can anyone think of more?

**Comment by squaremo** [comment]
> Generic coexistence incompatibility, e.g. ipvlan and macvlan
> Main/Meta/IPAM compatibility

Compatibility constraints (whether white-listing or black-listing) have the problem that they need constant intervention; e.g, plugin X does not white-list plugin Y, and the system refuses to let them operate together (until plugin X gets an update, or I take the risk of overriding the constraint).

That may be acceptable if new plugins don't come along that often (and if they can declare their own (in)compatibilities.)

**Comment by squaremo** [comment]
@steveeJ Is it worth splitting compatibility, arg specifications, and plugin composition into their own issues? Or do you think we should tackle them in one go, or use this as a discussion until we have concrete proposals?

**Comment by steveeJ** [comment]
@squaremo please split apart where you see fit and/or feel free to incluce a checkbox list in the first post!

**Comment by steveeJ** [comment]
I'll step back and let the @containernetworking/cni-maintainers decide the fate of this issue.

**Comment by squeed** [comment]
I actually think we, basically, did this. We have CHECK, as well as "capability arguments", which implement most of the proposals here.

I'm going to close this.
