### ISSUE TITLE
[Question]: What does "cniVersion" and "CNI_VERSION" do?

### ISSUE THREAD

**Issue by qianzhangxa** [containernetworking/cni#150]
Hi,

I'd like to know what "cniVersion" field means? Is it a required field in CNI network configuration? In https://github.com/appc/cni/blob/master/README.md#running-the-plugins, I do not see it in the example configuration, so it should be an optional field?

And what about the environment variable "CNI_VERSION" when invoking CNI plugin? How does it interact with "cniVersion", it's value has to be exactly same with the value of "cniVersion", right?

Thanks!

**Comment by dcbw** [comment]
@qianzhangxa See https://github.com/appc/cni/pull/80 for more details.  It's intended to ensure that if the CNI spec gets extended incompatibly in the future, that the runtime and plugin can intelligently handle a mismatch.  If the runtime passes a version number that indicates which CNI specification the arguments its passing conforms to, and if the plugin doesn't understand that version it can return a descriptive error.

**Comment by qianzhangxa** [comment]
Thanks @dcbw! I took a look at #80, it seems that PR only updated `SPEC.md`, did not change any code. And in https://github.com/appc/cni/blob/master/pkg/types/types.go#L59:L66, I do not see the `cniVersion` field yet, so the version mechanism in CNI has not been implemented, right?

**Comment by zachgersh** [comment]
@qianzhangxa I believe your confusion is actually warranted. I think the spec was changed but there was no associated code change. This really is a small bug that we would gladly take a PR for :dart:

**Comment by qianzhangxa** [comment]
Thanks @zachgersh for the clarification. Is anyone currently working on that PR? If not, can I take it? :-)

And can you please help answer my questions about `CNI_VERSION` and `cniVersion` below?
> And I am still confused about the environment variable CNI_VERSION and the field cniVersion in the network configuration. I think both of them are passed by container runtime to the plugin that it invokes (CNI_VERSION passed as environment variable, cniVersion passed as a field of the network configuration via stdin), right? Should container runtime make sure the value of them exactly same when invoking the plugin? And how does a plugin know if the version it can understand or not? The plugin can know it by checking CNI_VERSION or cniVersion? Thanks!

**Comment by zachgersh** [comment]
@qianzhangxa you can totally take the fix! As for why it is both specified as an ENV var and a argument to stdin, I can't really say. Maybe @steveeJ would know. Maybe we pick one and remove the other?

**Comment by qianzhangxa** [comment]
Yeah, I think we should just pick one.
@steveeJ, any comments? :-)

**Comment by steveeJ** [comment]
I can't find any references in the code, and I agree that we shouldn't keep both around. It's a decision to be made which we're going to use. Personally I like the attribute in the configuration better, because it allows to track for which CNI version a configuration has been written.

**Comment by qianzhangxa** [comment]
@steveeJ, I have another question: how can a plugin know if the version it can understand or not? Will we have version number in each plugin's code and have plugin to check if the version passed by runtime is compatible with its version in the code?

**Comment by bboreham** [comment]
I think this can be closed now: `CNI_VERSION` was removed from the docs and lots of mechanism to handle versions was added.
