### ISSUE TITLE
failed to find a unique veth name

### ISSUE THREAD

**Issue by errordeveloper** [containernetworking/cni#155]
This error message happens to appear when the interface inside the container already exists, and this is supposed to be unreachable code... not sure what's exactly going on here.

What I'm doing is:
```
echo '{
  "bridge":"cbr0",
  "ipMasq":true,
  "ipam":{"routes":[{"dst":"0.0.0.0/0"}],"subnet":"10.240.1.0/24","type":"host-local"},
  "isGateway":true,
  "name":"kubenet",
  "type":"bridge"
}' \
  | env \
    CNI_COMMAND=ADD \
    CNI_CONTAINERID=5709bbff004a100c0a69837654f9d42c93cca6ff070f7a2509f2ebffb68ffe2a \
    CNI_NETNS=/proc/23995/ns/net CNI_IFNAME=eth12 CNI_PATH=/opt/cni/bin:/opt/bridge/bin \
   /opt/cni/bin/bridge
```
And this command works the first time, but returns the "failed to find a unique veth name" on the second run. If I bump `CNI_IFNAME`, it works again.

**Comment by steveeJ** [comment]
> and this is supposed to be unreachable code

I assume you're referring to [this comment](https://github.com/appc/cni/blob/d19044896e06af0c9130963db0afe71c1b6620aa/pkg/ip/link.go#L64). While I don't like the code in question and your case indeed falls through, can you agree with me that your use-case isn't a valid one? You are requesting CNI to use the same interface name, which will undoubtedly clash.

**Comment by squaremo** [comment]
> While I don't like the code in question and your case indeed falls through, can you agree with me that your use-case isn't a valid one?

Right -- at the minute CNI makes it the responsibility of the caller to supply an unused interface name. While that's not ideal, I don't think it could be made completely foolproof.

**Comment by steveeJ** [comment]
> I don't think it could be made completely foolproof.
I agree. What we can do better right now is detect this error case in the first loop iteration and give more exact information in the error message.

**Comment by errordeveloper** [comment]
> What we can do better right now is detect this error case in the first loop iteration and give more exact information in the error message.

@steveeJ why isn't it caught by the default case?

**Comment by steveeJ** [comment]
@errordeveloper it falls into this case https://github.com/appc/cni/blob/d19044896e06af0c9130963db0afe71c1b6620aa/pkg/ip/link.go#L55, which is supposed to help with the interface name clashes of randomly generated names for the `peerName`.

**Comment by errordeveloper** [comment]
@steveeJ ah, of course, didn't realise this error is effectively ignored.

**Comment by steveeJ** [comment]
@errordeveloper volunteering? :-)

**Comment by steveeJ** [comment]
ping @errordeveloper, any plans to work on this still?
