### ISSUE TITLE
Documentation on vendoring

### ISSUE THREAD

**Issue by steveeJ** [containernetworking/cni#160]
We should agree on an official way to manage/declare the dependencies. Since #156 I assume we will not use godep, or would we @zachgersh? 

It would be nice to have a standardized and documented way, similar to this one from the rkt docs: https://github.com/coreos/rkt/blob/master/Documentation/hacking.md#managing-dependencies

**Comment by zachgersh** [comment]
This is interesting and I do really like what rkt has done documenting how to manage dependencies for the project. I may just drop a PR for our `CONTRIBUTING.md`.

Long story short - godep is still used for saving dependencies into the vendor folder and that is it. You no longer need to do anything like godep restore etc.

**Comment by squeed** [comment]
We no longer have ay dependencies; closing.
