### ISSUE TITLE
host-local ipam should allocate round-robin ips

### ISSUE THREAD

**Issue by freehan** [containernetworking/cni#194]
host-local ipam tends to allocate ips that are recently used. This sometimes cause unexpected behavior related to arp caching. 

If this sounds like a good idea, I will put together a PR. 

https://github.com/kubernetes/kubernetes/issues/24953

**Comment by freehan** [comment]
@dcbw @steveeJ

**Comment by dcbw** [comment]
Depending on how quickly containers are spawned, won't round-robin still be a problem with ARP caching?  It's certainly possible to cycle through all addresses within the ARP cache timeout.

**Comment by freehan** [comment]
It is much harder to exhaust the whole cidr range tough. Any alternatives you can think of?

**Comment by freehan** [comment]
Maybe sending gratuitous ARP on veth creation?

**Comment by freehan** [comment]
Another approach can be what docker did. Docker associates the mac address with ip. Meaning the container with the same ip always gets the same mac address.

**Comment by thockin** [comment]
I think both solutions are right.  Don't reuse IPs unless you need to and if you do reuse them, have a 1:1 IP:MAC relationship.

**Comment by freehan** [comment]
MAC address manipulation is easier to implement. Round robin ips requires refactoring which people may not like. 

Initial testing shows this fixes a bunch of flaky tests for kubenet.

**Comment by thockin** [comment]
I'm not that sympathetic to "the right thing to do is hard" :)  Maybe we
can not block on it, but it should be done, regardless.

**Comment by freehan** [comment]
Will submit a separate PR for round robin ip allocation
