### ISSUE TITLE
Make working on arm64 and ppc64le too

### ISSUE THREAD

**Issue by luxas** [containernetworking/cni#209]
When building for `arm64` or `ppc64le`, it fails with these messages:
```
# github.com/containernetworking/cni/pkg/ns
pkg/ns/ns.go:26: undefined: setNsNr
# github.com/containernetworking/cni/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/flock.go:18: undefined: Flock_t
vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14: undefined: Ucred
vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27: undefined: Ucred
vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42: undefined: Cmsghdr
```
The `ns.go` issue seems easy to fix, but the `golang.org/x/sys/unix` ones seems harder.
We'll need cni for these arches for Kubernetes

**Comment by luxas** [comment]
cc @pensu

**Comment by luxas** [comment]
The first one is easy, we just need to create some more files: https://github.com/opencontainers/runc/blob/master/libcontainer/system/setns_linux.go#L13-22

**Comment by luxas** [comment]
Checked the golang.org/x/sys dependency out and it's really old. Now the package has 155 commits, the vendored version has only 76, so a `godep update` will do

**Comment by steveeJ** [comment]
@luxas please submit a PR with the mentioned `godep update`. In the longterm we might want to include compilation for other architectures in our CI. For this purpose it would be shared the build steps, unless you're building this natively ;-)

**Comment by luxas** [comment]
I'm cross-compiling, and will send a PR as soon as I have time :)

**Comment by luxas** [comment]
Seems like c0d34c692f03f42b355cd3fe7a4ae28b2b5556eb fixed the SetNsNr issue.
I'm sending a PR now...

**Comment by luxas** [comment]
#241 
I think you can move this to `v0.4.0`

**Comment by luxas** [comment]
This is working now when #241 is merged. Thanks!
