### ISSUE TITLE
No Internet Access with Flannel Plugin

### ISSUE THREAD

**Issue by batikanu** [containernetworking/cni#242]
I use ubuntu 14.04 as host os and testing cni flannel plugin. The docker(v.1.11.2) containers which are started with cni flannel plugin don't have internet access whereas they work fine with cni0 bridge on the same host.
I use /run/flannel/subnet.env  as
{
    "name": "mynet",
    "type": "flannel"
}
I would be very pleased if you have working example.

**Comment by bboreham** [comment]
Is https://github.com/containernetworking/cni/issues/184#issuecomment-220549857 relevant?

**Comment by steveeJ** [comment]
> Is #184 (comment) relevant?

Thanks for the pointer @bboreham, I think this is exactly what @batikanu needs. I'll leave this open for a couple days to await feedback!

**Comment by rosenhouse** [comment]
It's been more than a couple days, closing!
