### ISSUE TITLE
Proposal: Support hypervisor container runtime for CNI

### ISSUE THREAD

**Issue by feiskyer** [containernetworking/cni#251]
## Overview

CNI is designed to provide a generic plugin-based networking solution for application containers on Linux. There are many container runtime implementations today. To isolate container networking from host, some of them are based on linux network namespace (e.g., [docker](http://github.com/docker/docker), [rkt](https://github.com/coreos/rkt) without lkvm), while others are based on hypervisor (e.g., [rkt with lkvm](https://github.com/coreos/rkt/blob/master/Documentation/running-lkvm-stage1.md), [HyperContainer](https://github.com/hyperhq/hyperd)). Current CNI design already supports runtimes based on network namespace, but not hypervisors. So this proposal amis to add hypervisor runtime support to CNI.
## Considerations

There many differences between hypervisor and linux network namespace on networking:
- Hypervisor has its own network stack, there is no need to create a network namespace for hypervisor. Instead, CNI should create a tap device for hypervisor.
- Since the network is configured inside hypervisor, CNI network plugin couldn't configure ip address directly outside. Instead, CNI should prepare the network device (e.g., create bridge and connect a tap device), then pass the network information (including the device, IP address, gateway, routes, etc.) back to the runtime, and let runtime do remaining configuration work.
## Design

To support hypervisor-based runtimes, a few changes should be made in CNI:
- Let CNI be aware of runtime type (hypervisor or netns)
- Configure tap device instead of veth pair for hypervisor-based runtime
- Pass network information back to runtime
### Aware of runtime type

Add a new field `UsesTapDevice` in `RuntimeConf`, e.g.:

``` go
type RuntimeConf struct {
    // The ID of the container
    ContainerID string
    // If set, a tap device instead of veth pair should be created
    UsesTapDevice bool
    // The network namespace path. 
    // Optional. Only need if IsHypervisor is not set.
    NetNS       string
    // Name of the interface inside the container. 
    IfName      string
    // Extra arguments
    Args        [][2]string
}
```
### Configure tap device instead of veth pair

This will be the job of network plugins. Since there are no network namespace, network plugin should create a tap device directly on host. Existing plugins would be refactored to create tap device for hypervisor runtime. 

The network configuration and IPAM could keep as is, so container's ip address could be allocated as before.
### Pass network info back to runtime

Dan has already started this on [#145](https://github.com/containernetworking/cni/pull/145). 

CC @dcbw @rosenhouse @squaremo @steveeJ @tomdee

**Comment by steveeJ** [comment]
@feiskyer
Thank you for this nice proposal. I'd like to collect feedback from @jellonek and @pskrzyns.

**Comment by pskrzyns** [comment]
cc @lukasredynk @jjlakis

**Comment by gao-feng** [comment]
Who will do the job that attach tap device to vm?

**Comment by feiskyer** [comment]
@gao-feng CNI doesn't care the hypervisor implementation details, it just know the runtime is hypervisor-based and wants a tap device instead of veth pair. Container runtime should attach this tap device to hypervisor.

**Comment by feiskyer** [comment]
ping @steveeJ

**Comment by lukasredynk** [comment]
I've looked into #145 and it looks a bit heavy in terms of changes to interface, adding env like "CNI_VIRT" and returning tap index shouldn't be sufficient?

**Comment by feiskyer** [comment]
@lukasredynk Adding a env may work, but not so explicit. All current cni plugins are supposed to be netns-based, it needs to know the runtime is hypervisor explicitly.

Just returning tap index is not enough because we don't expect every plugin interacting with hypervisor directly. Instead, cni returns the created tap device and related ip address/mask/gateway/dns back to runtime, and let runtime itself configure those into hypervisor.

**Comment by lukasredynk** [comment]
Sorry, I wasn't precise, yes, I agree. The scheme I'm thinking of:
1. Set CNI_VIRT (optional)
2. Run plugin (from plugins/main)
3. Plugin checks if CNI_VIRT set 
- CNI_VIRT not set: no changes in flow
- CNI_VIRT set: creates tap instead of veth
4. Plugin executes IPAM plugin (and passes CNI_VIRT if set)
- CNI_VIRT not set: no changes in flow
- CNI_VIRT set: only reserves IP and returns information about how to configure iface in VM
5. Top-most plugin returns:
- CNI_VIRT not set: no changes in flow
- CNI_VIRT set: to the usual output would be added additional param "Iface *unit" in types.IPConfig

**Comment by feiskyer** [comment]
@lukasredynk A new environment variable (e.g. `CNI_VIRT`) is indeed required, but only this one environment variable is not enough:

* A lot of external cni plugins are using libcni, which should of course need to know whether the runtime is based on hypervisor
* `invoke.Args` and `CmdArgs` also needs to know whether or not the runtime is based on hypervisor

BTW, I'm not satisfied with `IsHypervisor bool`, do you have any suggestions about this filed? Maybe `Virtualized bool`?

**Comment by lukasredynk** [comment]
I've started work on code I could show to move discussion further, but for now I've added to `pkg/skel/skel.go` `"CNI_VIRT"` to list of env variables put into `CmdArgs`. First I was thinking about providing basic implementation-proposal of ptp and bridge plugins, but I'm still working on it, it looks like netlink lib version should be bumped, because the version used doesn't support creating tun/tap devices. Thank you for pointing out `invoke.Args`, I totally missed it, I thought that adding filed in `pkg/skel/skel.go` would be sufficient.

About `IsHypervisor bool`: maybe `TunTap bool` defaulting to `false`? Because maybe there'll be situations, when there'll be usecase where tap would be preferred over veth and won't be related to hypervisor field? (with emphasis on *maybe*).

**Comment by jellonek** [comment]
@feiskyer to use tap devices you don't have to use virtualization so IMO instead of `Virtualized` we shoud use `UsesTapDevice`.

**Comment by feiskyer** [comment]
@lukasredynk @jellonek Thanks. Updated proposal to `UsesTapDevice` instead of `IsHypervisor`.

**Comment by lukasredynk** [comment]
*Very* early and *very* WIP branch with creating and configuring tap device for ptp plugin: https://github.com/lukasredynk/cni/pull/1/files Most of changes here are related to updating netlink library (version from vendor can't handle tap devs).

**Comment by feiskyer** [comment]
@lukasredynk Change virt to UsesTapDevice and file a PR?

**Comment by lukasredynk** [comment]
@feiskyer Ok, it's here: https://github.com/containernetworking/cni/pull/271

I've tested this with rkt-kvm and it's working, at least for default-restricted network.

**Comment by lukasredynk** [comment]
RFC: how should the interface be named? I think it should be different from "veth*" to not mix different device types, maybe "tap*", where "*" is suffix generated the same way as is for veth-type interfaces. What do you think about it?

**Comment by feiskyer** [comment]
@lukasredynk Agree on `tap*`.

**Comment by lukasredynk** [comment]
I've updated PR:
- changed CNI_VIRT to CNI_USE_TAP
- added codepaths to libcni
- refactored tap creation

Only thing missing here is merging pending PR in netlink repo.

**Comment by thockin** [comment]
I hate to be contrarian, but this seems like a wrong turn, to me.  Not all CNI plugins are going to use veth.  This feels like it is taking inside information and putting it on the outside.  You are now making every network plugin responsible for understanding tap devices?

Why can't this be done ENTIRELY inside a CNI plugin?   Do we need some affordance in the CNI API to give a clue to the plugin, I can maybe buy that.  But I am having a hard time with this, overall.  It just doesn't feel right.

**Comment by feiskyer** [comment]
> I hate to be contrarian, but this seems like a wrong turn, to me. Not all CNI plugins are going to use veth. This feels like it is taking inside information and putting it on the outside. You are now making every network plugin responsible for understanding tap devices?

Yes, this proposal will make every cni plugin responsible for understanding tap devices. It makes sense because CNI is a general network interface for all containers (if I'm not wrong), including hypervisor-based runtimes.

> Why can't this be done ENTIRELY inside a CNI plugin? 

It could, but the plugin is not general any more. In general, all network plugins should work for all runtimes which support CNI.

**Comment by thockin** [comment]
> all network plugins should work for all runtimes

I think this is a really dubious starting position.  You can not reasonably
expect all container vendors to support this.

Does someone have a diagram or a thorough explanation of the networking
setup for hypervized runtimes?  I'd like to see an example of how the
devices chain together, and how the IP routing is configured.

**Comment by lukasredynk** [comment]
Following @jellonek's advice I've prepared PR (https://github.com/containernetworking/cni/pull/274) with updated netlink (which includes my changes) and after merging it I'll rebase original PR with PTP plugin.

@thockin CNI plugin can't setup network inside VM because it's always run on the host machine. It's not a problem for containers based on systemd-nspawn to setup networking before spawning container because host and container share kernel space, but in case of VM there's no direct way to create virtual interface (how it would be connected to network on host?), assign IP address and setup routing via syscalls (what effectively CNI does), because there's no way to do it before spawning VM. Also hypervisors can't attach veth devices to VM's (which are currently created by ptp, bridge and flannel plugins).

You could take a look on networking in rkt (in github.com/coreos/rkt/networking: networking.go and kvm.go ): current implementation uses CNI for nspawn containers and for VM-based containers there's custom path (using parts of CNI codebase) setting up tap, getting routes, acquiring IP and passing this information back to hypervisor (tap device name, via cli). Also there're created systemd unit files which VM's systemd uses to setup all networking. Actually all plugins are supported by this "bypass", but it a) partially duplicates CNI functionality b) makes it difficult to maintain.

> You can not reasonably expect all container vendors to support this.
How this is concern for container vendors? Creating tap is opt-in. Before passing specific, optional flag to CNI all will work like before. Actually it's big gain for projects which want to handle network configuration via CNI and also need tap-based networking for specific cases.

**Comment by jellonek** [comment]
To be honest - not all plugins (`ipvlan` is not supported). Still moving this code from `rkt` into `cni` solves two things - firstly code duplication on mentioned projects and in second place - provides same functionality to other VM based runtimes like HyperKube or vocker.

**Comment by thockin** [comment]
To be clear - I get why this is better for hypervized runtimes.  I am more
concerned about the ugliness of the API and the idea that existing drivers
should implement both modes.  It just feels wrong.  The factoring doesn't
smell right to me.

If I have a CNI plugin that handles OVS - can I link a tap device into my
OVS?

Can I use a tap device on Calico?  Weave?  Contiv?

Why is this better than a set of new CNI plugins that explicitly support
ONLY tap devices?  Is it the "need an open FD" issue?

**Comment by feiskyer** [comment]
@thockin Creating tap is opt-in. Existing drivers could choose to only support netns-based containers as is today. Could you explain why it is ugliness?

> If I have a CNI plugin that handles OVS - can I link a tap device into my OVS?

Of course could. Only with a minor change: when connecting to the container, create a tap device instead of veth pair.

> Can I use a tap device on Calico?  Weave?  Contiv?

This is also yes if Calico/Weave/Contiv add support of tap devices.

> Why is this better than a set of new CNI plugins that explicitly support ONLY tap devices?  Is it the "need an open FD" issue?

Let me think some

* Reduce code duplication
    * one binary and code base work for both
    * network plugins may perform a number of steps to setup network, e.g. allocate ip address, create bridges, setup iptables rules, setup tunneling, connect the bridge to container (by veth pair or tap device). Only the last step is different. All other steps are totally same for both.
* Expand the scope of CNI, so it could support all types of runtimes, whether it is netns or hypervisor. (Or else, we may need another CNI, dedicated for tap devices)
* Consistent UX when switching runtimes, so users don't need to rewrite a new plugin to integrate with existing network infrastructures

**Comment by lukasredynk** [comment]
And *only* plugins affected by this changeset are:
- ptp
- bridge
- macvlan
- flannel (because internally wraps bridge plugin)

And those are from main CNI repository. If external plugins would want to support creating tap they could, but this isn't mandatory. AFAIK Calico uses only ipam for IP management (manages veth's by itself), I'm not sure about Weave but after quick look into their documentation it appears that way. 

So: there're no changes for external plugins like Calico/Weave/Contiv.

**Comment by thockin** [comment]
On Wed, Aug 3, 2016 at 4:28 AM, Pengfei Ni <notifications@github.com> wrote:
>
> @thockin Creating tap is opt-in. Existing drivers could choose to only support netns-based containers as is today. Could you explain why it is ugliness?

You're taking a detail - the specific type of network device - and
making it part of the API.  Once you support this, you have no grounds
on which to reject the next different idea, and your APi devolves into
a mess of conditionals and optional-if fields.  There's elegance and
simplicity to opaqueness.  This doesn't feel like the simplest
possible solution.

Can we do something where the hypervisor exists in a netns (in the
host os) and the net plugin is the same in all cases, and delegate the
hypervisor complexity to only appear in hypervised cases?

> If I have a CNI plugin that handles OVS - can I link a tap device into my OVS?
>
> Of course could. Only with a minor change: when connecting to the container, create a tap device instead of veth pair.
>
> Can I use a tap device on Calico? Weave? Contiv?
>
> This is also yes if Calico/Weave/Contiv add support of tap devices.

MacVLAN?  IPVLAN?  My point is that you already force users to
consider whether their plugin supports a particular mode of operating
- why make that part of the API.

> Why is this better than a set of new CNI plugins that explicitly support ONLY tap devices? Is it the "need an open FD" issue?
>
> Let me think some
>
> Reduce code duplication

Not an argument.  Libraries are fine.

> one binary and code base work for both

same answer.  You still approximately double the test load

> network plugins may perform a number of steps to setup network, e.g. allocate ip address, create bridges, setup iptables rules, setup tunneling, connect the bridge to container (by veth pair or tap device). Only the last step is different. All other steps are totally same for both.

This is the previous arguments, just restated :)

> Expand the scope of CNI, so it could support all types of runtimes, whether it is netns or hypervisor. (Or else, we may need another CNI, dedicated for tap devices)

My point is that tap is a VERY SPECIFIC technology.  As soon as
something better comes along, this API is obsolete.  The same could be
said of netns (and in fact, libnetwork doesn't even expose netns, if I
recall) but that's at a lower level, so less risky to my eyes.

> Consistent UX when switching runtimes, so users don't need to rewrite a new plugin to integrate with existing network infrastructures

but they actually DO have a different plugin.  It might use 80% the
same code, but it behaves differently and performs differently, so it
is different.

**Comment by jellonek** [comment]
Also user could have same configuration for different runtimes.

**Comment by rosenhouse** [comment]
Not to pile on too much, but I would also ask how we plan to test this hypervisor support in our CI system?  Travis lets us create netns and execute plugins in those netns.  Is there a CI environment we could use to exercise the hypervisor code paths?

**Comment by feiskyer** [comment]
@steveeJ @dcbw What's your opinions about this?

**Comment by squeed** [comment]
Hm.

Rather than complecting the 'ADD' command to have two fairly divergent semantics, what about adding an additional command to the spec? Something like 'CONFIGURE', which passes an already-initialized interface (say, a tap created by the hypervisor) to be configured by a CNI plugin?

**Comment by jellonek** [comment]
This would require that hypervisor should be running before CNI plugin is called (and is exactly quite similar to how current implementation of kvm flavored rkt is doing).

With current proposal (and initial implementation in #271) you can run for example from kubernetes network preparation process and then pass results to any hypervisor based runtime (this could be kvm flavored [rkt](https://github.com/coreos/rkt), [hyperd](https://github.com/hyperhq/hyperd) or something other on what i'm working now ;) ).

Still having a possibility to pass network device (could be prepared veth/tap/macv(lan|tap)) seems to be easy to implement as additional CNI "main" plugin. This could be also reused by existing plugins, like already they are calling IPAM plugins.

That way we would have chain like:
* prepare interface (this could be done by plugin or external thing) which calls:
 * assign ipv4/ipv6 required configs (addressing/routing/iptables) on particular device which calls:
   * IPAM

Actually first two steps are combined in [main](https://github.com/containernetworking/cni/tree/master/plugins/main) plugins.

If someone is interested in this - we could discuss this, but IMO in separate issue.

**Comment by feiskyer** [comment]
Closing this in favor of #420.
