### ISSUE TITLE
Proposal of BaGPipe BGP cni plugin

### ISSUE THREAD

**Issue by murat1985** [containernetworking/cni#252]
I wrote a plugin using your libraries to talk to [BaGPipe BGP](https://github.com/Orange-OpenSource/bagpipe-bgp) daemon. That allows to leverage container networking using VXLAN and BGP. 

I am wondering do you accept new plugins? I wrote it pretty much using bridge plugin code. 

https://github.com/murat1985/bagpipe-cni

Thank you

**Comment by leodotcloud** [comment]
@murat1985 Probably you can edit the[ README file](https://github.com/containernetworking/cni/blob/master/README.md) to include link to your CNI plugin repo and submit a PR. That way it's easier to get it reviewed and merged.

**Comment by murat1985** [comment]
thanks @leodotcloud sounds good
