### ISSUE TITLE
host-local and large subnets

### ISSUE THREAD

**Issue by vixns** [containernetworking/cni#256]
with a range larger than /24, eg : 
```
{
    "name": "test",
    "type": "bridge",
    "bridge": "cni0",
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.1.0.0/16",
        "rangeStart": "10.1.2.2",
        "rangeEnd": "10.1.4.254",
        "gateway": "10.1.0.1",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]
    }
}
```

host-local allocate bad ips, eg 10.1.2.255 or 10.1.3.0

**Comment by bboreham** [comment]
Those addresses are "bad" in a /24 network, but perfectly fine in a /16.

**Comment by dcbw** [comment]
Yeah, true.  @vixns what problems is this causing in your network?

**Comment by vixns** [comment]
@bboreham you're right, i had some /23 from previous tests on several nodes. I've cleaned up to only have a global /16, seems far better.
@dcbw i'm using the network/cni mesos isolator, a bridge+host-local on each node, connected over a private lan over a vlan.

This pr is not needed, i'm closing it, thanks for your time and sorry for the noise.
