### ISSUE TITLE
bridge: does not set the gateway on the route

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#27]
First raised in https://github.com/coreos/rkt/issues/862

bridge does correctly sets the IP on on the bridge (if `isGateway` is true) but not on the route.

**Comment by eyakubovich** [comment]
This is actually per current spec:
`gateway` is the default gateway for this subnet, if one exists. It does not instruct the CNI plugin to add any routes with this gateway: routes to add are specified separately via the routes field.

However this will cause a lot confusion and needs to be changed.

**Comment by steveeJ** [comment]
I suggest we add a field `isDefaultGateway` that causes an additional route with `0.0.0.0/0` for IPv4 for now. The default for this field shall be true since that's what most people expect as you already pointed out.
