### ISSUE TITLE
Proposal: use of combined binary (busybox like).

### ISSUE THREAD

**Issue by jellonek** [containernetworking/cni#275]
As in subject and as I mentioned on irc channel - busybox like or [hyperkube](https://github.com/kubernetes/kubernetes/tree/master/cmd/hyperkube) like approach could reduce size of our distributed files. At the moment `cni` binaries used in `rkt` weight ~40M what could be probably nicely reduced - impacting whole `stage1.aci` size - and this could have an impact on download/unpack time.

In addition to already existing in busybox/hypercube approach of using symlinks/hardlinks (argv[0] in general) as also to choosing particular plugin by switch passed to common binary - @fabiand on irc added proposal to optional support plugin choosing using env variable as a key.

What do you think about this?

**Comment by jellonek** [comment]
PTAL

**Comment by eyakubovich** [comment]
Is there any Golang tooling to produce busybox like binary out of individual projects each having a `main` or does it require code change?

**Comment by sgotti** [comment]
@eyakubovich not sure about a tool but in rkt (also used by acbuild) we have github.com/coreos/rkt/tree/master/pkg/multicall for doing this. It was born to call rkt from rkt with another main function for doing chrooted extraction but its basic function is to register a function based on the provided process arg[0].

**Comment by jellonek** [comment]
I don't know if there is such tool, but kubernetes shown that this could be done with quite little effort.

@sgotti - it's also interesting in scope of similar "joining" binaries in `rkt` mentioned by me on irc, i mean - `gc`, `init`, `stop`, in kvm flavor also `enter_kvm`.

**Comment by eyakubovich** [comment]
I was wondering if it's possible not to change code and have this be a packaging issue and not CNI proper.

**Comment by dcbw** [comment]
Yeah, this is a tooling issue (because Go) and it would be nice not to have to work around Go's love of static compilation in CNI code.  That may not be possible, but having to re-architect a project because the toolchain is quite sub-optimal for some cases is kinda icky.

**Comment by jellonek** [comment]
Yeah, I also think that this would require too much odd interference in shape of plugins, so after considering a bit about this - I'm closing this issue.

Maybe later we could come back to this idea, in time of architectural rethinking of project.
