### ISSUE TITLE
Documentation on "delegate"

### ISSUE THREAD

**Issue by asridharan** [containernetworking/cni#276]
I see the "delegate" construct being used in the `flannel` plugin, but couldn't find any documentation on the "delegate" construct in the CNI spec? I think this is a pretty useful functionality and would be great to document how plugins are supposed to use this construct, and how operators can specify them in their CNI spec.

**Comment by steveeJ** [comment]
@asridharan 

The delegate field is an implementation detail of the flannel plugin. Plugins are free to declare any fields that are not used within the specification. I can see the point of the delegate-
pattern as a generic way to do such things, but for now it is beyond the specification's scope. One of the other @containernetworking/cni-maintainers might have additional $0.02 on this topic.

That said, do you think the delegate field for the flannel plugin is sufficiently documented?

**Comment by asridharan** [comment]
Thanks @steveeJ 
I think it can do with a little bit more documentation (maybe highlight that it is specific to flannel). I was under the impression that the delegate is something more generic to the CNI spec. Also, I guess going through the documentation and using it people can figure out the various backend plugins that you can invoke through `delegate`, but making that more explicit would help as well. This would help clarify the fields you can set within the delegate dict.

**Comment by rkamudhan** [comment]
@asridharan I think, it is documented how to use ipvlan instead of bridge in the flannel using the delegate option.

**Comment by asridharan** [comment]
@rkamudhan. Yup I think we can close this issue. There are enough examples here to explain how to use the delegate model.
