### ISSUE TITLE
IP can't be recycled 

### ISSUE THREAD

**Issue by wulibin163** [containernetworking/cni#278]
if a container exit abnormal , ip can not be recycled

**Comment by philips** [comment]
Can you provide more information and ideally a test case?

**Comment by dcbw** [comment]
@wulibin163 if the container exits abnormally, the runtime controlling CNI ADD/DEL is expected to call DEL to ensure the IP configuration the container used is released.  I seem to recall there were fixes recently for some missing cleanups though, like #230 and #205

**Comment by squeed** [comment]
This is mostly fixed:
1. IPAM can use a different datadir, so you can point it at a tmpfs volume if applicable
2. Deletes are idempotent

Closing this.
