### ISSUE TITLE
CNI bridge plugin should set the bridge MAC address explicitly 

### ISSUE THREAD

**Issue by freehan** [containernetworking/cni#285]
Bridges where the MAC is not explicitly set will adopt the lowest MAC address of the attached veths. This means that when you rollout a new container with a veth lower than all those currently existing, it will change the MAC address of cbr0, and delete all of the existing connection tracking entries for flows that used the old MAC address.

ref: https://github.com/kubernetes/kubernetes/issues/30783

**Comment by leodotcloud** [comment]
Since it's not possible to always get the lowest MAC address to the bridge, a better solution would be to have an option to disable STP by default and leave an option to turn on for advanced users who know what they are up to by enabling STP. What do you think @freehan?

**Comment by bboreham** [comment]
How does disabling STP address the problem?  Does it prevent the bridge from changing MAC?

**Comment by squeed** [comment]
As it stands right now, we always set the bridge MAC address to something that is a function of the bridge IP address. However, this is poorly written for IPv6. So, this issue is currently resolved, but we need to make sure it remains fixed.
