### ISSUE TITLE
Specify which environment variables are required and which are optional.

### ISSUE THREAD

**Issue by asridharan** [containernetworking/cni#286]
Currently the CNI SPEC lists the environment variables that can be read by the CNI plugins but does not specify which of these variables are required and which of them are optional. For e.g., it is implicit that the CNI_ARGS field is optional, and it has been mentioned that the CNI_CONTAINERID can be optional, however the status of CNI_IFNAME is not clear.

As with the JSON config it would be great if we could explicitly state if the environment variables are optional or required.

**Comment by rosenhouse** [comment]
Fair question.  The current source of truth is: 
- [ADD](https://github.com/containernetworking/cni/blob/3450f08611ade3104f05846caad6b59651c7c4d5/pkg/skel/skel_test.go#L122-L128)
- [DEL](https://github.com/containernetworking/cni/blob/3450f08611ade3104f05846caad6b59651c7c4d5/pkg/skel/skel_test.go#L209-L216).

On reviewing those, I noticed that the `CNI_CONTAINERID` env var had a typo, and just opened #308 to resolve that.

I think we'd welcome a PR to the spec.md to make this more visible.

Closing for now, feel free to re-open if there's more discussion to be had.
