### ISSUE TITLE
CNI bridge plugin fails to read a bind mounted network namespace in CentOS 7 

### ISSUE THREAD

**Issue by asridharan** [containernetworking/cni#288]
We are running Mesos on a CentOS7 with Kernel 3.10

The following check:
https://github.com/containernetworking/cni/blob/master/pkg/ns/ns.go#L104

seems to trip the CNI plugin. The `getNS` call expects a network namespace as a directory `ns/` while in Mesos we bind mount the process network namespace to a file. 

The plugins works fine on distros such as CoreOS and Ubuntu 14.04 which have a higher kernel version:

Why can't we check `/ns` instead of `ns/`? The check makes an explicit assumption that the network namespace will be directory which is what is causing this issue.

This is the error, we see from the CNI bridge plugin:
```
"msg": "failed to open netns \"/run/mesos/isolators/network/cni/d87e06fd-13b4-42ce-b767-5c0619247f51/ns\": path \"/run/mesos/isolators/network/cni/d87e06fd-13b4-42ce-b767-5c0619247f51/ns\" doesn't contain \"ns/\""
"code": 100
```

**Comment by jieyu** [comment]
I suggest we completely remove this check. As @asridharan pointed out in the PR, namespace handles can be bind mounted. Container runtime might choose to do the bind mount to keep the namespace open. This is a very common practice.
