### ISSUE TITLE
how to disable ipv6 in ipvlan interfaces

### ISSUE THREAD

**Issue by huxos** [containernetworking/cni#289]
i added the tuning config to disable ipv6 but it dosn't work.

```
{
    "name": "disableipv6",
    "type": "tuning",
    "sysctl": {
        "net.ipv6.conf.all.disable_ipv6": "1",
        "net.ipv6.conf.default.disable_ipv6": "1"
    }
}
```

there are some error like this: 

Aug 25 09:39:20 l-010000106062-docker kubelet[27870]: E0825 09:39:20.192762   27870 docker_manager.go:345] NetworkPlugin cni failed on the status hook for pod 'passportweb-147208913
Aug 25 09:39:20 l-010000106062-docker kubelet[27870]:  with error: exit status 1
Aug 25 09:39:20 l-010000106062-docker kubelet[27870]: E0825 09:39:20.196561   27870 docker_manager.go:345] NetworkPlugin cni failed on the status hook for pod 'pub' - Unexpected com
Aug 25 09:39:20 l-010000106062-docker kubelet[27870]:  with error: exit status 1
Aug 25 09:39:21 l-010000106062-docker kubelet[27870]: E0825 09:39:21.219194   27870 docker_manager.go:345] NetworkPlugin cni failed on the status hook for pod 'passportweb-147208913
Aug 25 09:39:21 l-010000106062-docker.jumei.com kubelet[27870]:  with error: exit status 1

**Comment by bboreham** [comment]
@huxos a lot of work has been done on ipv6; if it still isn't working for you please open at new issue in the https://github.com/containernetworking/plugins repo
