### ISSUE TITLE
Should plugin DEL ever error?

### ISSUE THREAD

**Issue by rosenhouse** [containernetworking/cni#309]
Issue #306 raises an interesting question that applies generally to all plugins: how should runtimes react if an `ADD` fails?

One possibility is for `DEL` to be best-effort idempotent.  It tries to clean-up any & all left-over resources and swallows any errors that might arise if a resource was never created in the first-place.

Then we could recommend that a runtime call `DEL` after a failed `ADD`.

**Comment by dcbw** [comment]
Note that skel.go needs to be changed here too, specifically:
```
                {
                        "CNI_NETNS",
                        &netns,
                        reqForCmdEntry{
                                "ADD": true,
                                "DEL": false,
                        },
                },
```

Since we should still try to clean things up even when the netns has gone away.

**Comment by bboreham** [comment]
We could have `CNI_NETNS==""` mean "clean up what you can, but there's no namespace so don't worry about that".

**Comment by dcbw** [comment]
Though we could just do this now by making the internal plugins do best-effort cleanup, without changing the spec...  not sure if we'd consider that a material spec change or not.

**Comment by bboreham** [comment]
The phrasing "tries to clean-up any & all left-over resources" - is that meant to mean "... relating to the specific container ID supplied", or more broadly, clean up anything that seems to be left-over?  The latter sounds dangerous.

I think I'm ok with best-efforts meaning "I looked for resources assigned to that container ID; didn't find anything; returning success"; I would still like to error on a completely invalid parameter.

**Comment by dcbw** [comment]
@bboreham yes, I would expect that the operation would still be scoped to the specific container ID.

**Comment by chenchun** [comment]
> add this as a spec requirement, not just a recommendation

+1 of adding this as a spec requirement, and we could still keep the error return of `DEL`.
Make `DEL` return nothing means it can't complain any mistakes during cleanup.

**Comment by jieyu** [comment]
+1 on making this a spec requirement.

It's very hard for container runtime to react if cleanup fails. It has no idea if it should proceed with the rest of the cleanup or not.

**Comment by bboreham** [comment]
The spec was changed in #346 to say "Plugins should generally complete a DEL action without error even if some resources are missing [...] even if the container network namespace no longer exists"

So I think this should be closed.

**Comment by rosenhouse** [comment]
Agreed.  There is outstanding work to make the plugins actually behave this way.

**Comment by bboreham** [comment]
FYI Kubernetes 1.6 beta seems to rely on plugins not erroring on DEL - see https://github.com/weaveworks/weave/pull/2801#issuecomment-286807890
