### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#31]
The spec does allow for IPv6 but the plugins only support IPv4 (with the exception of host-local).

Tracking:
- [ ] bridge
- [ ] ptp
- [ ] macvlan
- [ ] ipvlan
- [ ] host-local #131

**Comment by NeilW** [comment]
I'm particularly interested in adding IPv6 support to macvlan since plugging the containers straight into the upstream ethernet network allows stateless address auto configuration to work - where a Host virtual machine is allocated a /64 on its network.

**Comment by bboreham** [comment]
* `host-local` in https://github.com/containernetworking/plugins/pull/12
* `bridge` was done in https://github.com/containernetworking/plugins/pull/10
* `ptp` in https://github.com/containernetworking/plugins/pull/25
* `macvlan` and `ipvlan` picked the support up as part of the above
