### ISSUE TITLE
flannel plugin and hairpin mode

### ISSUE THREAD

**Issue by TerraTech** [containernetworking/cni#320]
Running on: CoreOS-1185.2.0 and quay.io/coreos/hyperkube:v1.4.3_coreos.0

For the kubelet:
```
[..snip..]
--network-plugin=cni \
--hairpin-mode=hairpin-veth \
[..snip..]
```
I was looking at the docs at: https://github.com/containernetworking/cni/blob/master/Documentation/flannel.md

With the bridge config being generated, is it possible to enable _hairpin_ mode via some flannel plugin configuration setting?

/etc/kubernetes/cni/net.d/10-flannel.conf
```json
{
  "name": "podnet",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
```

I ran into a problem with Kubernetes addon for https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring/influxdb

In that the INFLUXDB_SERVICE_URL=http://monitoring-influxdb:8086 which won't work unless hairpin mode is turned on.  I found there were two alternate ways to fix this:
1. INFLUXDB_SERVICE_URL=http://_localhost_:8086
2. enable hairpin mode on the pod's veth interface so that it could use the service IP address
I did confirm on the minion by manually enabling it with:
```sh
# brctl hairpin cni0 veth62735bbd on
```
TIA!

**Comment by TerraTech** [comment]
After noticing that 'isDefaultGateway' was a bridge command, it dawned on me that I might be able to configure this via flannel config's delegate stanza:
```
{
  "name": "podnet",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true,
    "hairpinMode": true
  }
}
```
I updated the cloud config and rebooted the minion, created the test pod and the veth interface now has 'hairpin on'.

**Comment by TerraTech** [comment]
Which leads to my next question, does anyone know if you can define in a kubernetes pod definition certain CNI configuration items perhaps through an annotation?  e.g. I'd like for only certain deployments/pods/etc to have hairpin enabled instead of it being global.

**Comment by bboreham** [comment]
@TerraTech that is not presently implemented.

Also it is a Kubernetes question so doesn't belong here in the CNI repo.  The closest I can see in the Kubernetes repo is https://github.com/kubernetes/kubernetes/issues/19766, but the conversation has snaked around a lot.

https://github.com/kubernetes/kubernetes/pull/29009 introduced code to use the feature for the `kubenet` network, but not for general CNI plugins.

**Comment by JamiKarvanen** [comment]
I run v1.6.4 kubelet with these settings:
--network-plugin=cni
--hairpin-mode=hairpin-veth

Kubelet logs: Hairpin mode set to "hairpin-veth"

Flannel is self hosted (running as a DaemonSet) and my cni-conf looks like this:
    {
      "name": "cni0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true,
        "hairpinMode": true
      }
    }

Neither kubelet or flannel plugin sets the hairpin mode, so all the veth-interfaces have it disabled. Should this setup work, am I missing something?

**Comment by bboreham** [comment]
The fact that Kubernetes stopped setting it is recorded at  https://github.com/kubernetes/kubernetes/issues/45790

The `delegate` part of the Flannel config is supposed to call the `bridge` plugin, which gained this capability in 89ab9299abcc165ad41189c407f8691eb95f8262 around a year ago.

**Comment by dnardo** [comment]
@JamiKarvanen It should work as bboreham mentioned flannel should handle this, kubelet will not if you set the network-plugin to "cni"

A similar issue came into kubernetes and after setting the correct hairpinMode : true that seemed to fix their issue.  This was also on 1.6
https://github.com/kubernetes/kubernetes/issues/43966#issuecomment-294931063

I would remove this flag --hairpin-mode=hairpin-veth if you are doing network_plugin=cni and I'm also curious to see the results of 
/sys/devices/virtual/net/cni0/brif/veth*/hairpin_mode

**Comment by JamiKarvanen** [comment]
@dnardo I'm using the latest version (v0.5.2) of the CNI-plugins. I have tried with and without the --hairpin-mode flag and results are the same: all veth* interfaces have hairpin_mode set to 0. So it seems that the bridge plugin never sets the hairpin mode.

Any ideas for debugging this further?

**Comment by dnardo** [comment]
@JamiKarvanen 
I would first see if bridge plugin is working correctly, since flannel delegates to bridge has bboreham stated:
I would just manually try bridge plugins like this:

# keichan [/opt/cni/bin] cat test.conf 
{
	"name": "mynet",
	"type": "bridge",
	"bridge": "mynet0",
	"isDefaultGateway": true,
	"forceAddress": false,
	"hairpinMode": true,
	"ipam": {
		"type": "host-local",
		"subnet": "10.10.0.0/16"
	}
}
 
# keichan [/opt/cni/bin]  ls
bridge  cnitool  dhcp  flannel  host-local  ipvlan  loopback  macvlan  net.conf  noop  ptp  test.conf  tuning
 
# keichan [/opt/cni/bin] export CNI_COMMAND=ADD
 
# keichan [/opt/cni/bin]  export CNI_NETNS=/var/run/netns/test
 
# keichan [/opt/cni/bin]  export CNI_IFNAME=cni0
 
# keichan [/opt/cni/bin]  export CNI_PATH=/opt/cni/bin
 
# keichan. [/opt/cni/bin]  ip netns add test
 
# keichan [/opt/cni/bin]  cat test.conf |./bridge                                 
{
    "ip4": {
        "ip": "10.10.0.3/16",
        "gateway": "10.10.0.1",
        "routes": [
            {
                "dst": "0.0.0.0/0",
                "gw": "10.10.0.1"
            }
        ]
    },
    "dns": {}
}#                                                                                                                                           
# keichan [/opt/cni/bin] → cat /sys/class/net/mynet0/brif/veth568a68fa/hairpin_mode 
1


If that works, then it seems like it may be something with the flannel delegating to the bridge plugin.
If that doesn't work then maybe something with your environment.

**Comment by JamiKarvanen** [comment]
@dnardo Thanks! I tested this and the bridge plugin works as expected and sets the hairpin_mode successfully, so the delegation is not working correctly

**Comment by soumyapanigrahi-k8s** [comment]
@JamiKarvanen do we have a workaround/fix to this issue. Even I am facing the exact same issue...
