### ISSUE TITLE
Unable to delegate IPAM routes

### ISSUE THREAD

**Issue by h0tbird** [containernetworking/cni#333]
I would like to setup IPAM routes via `delegate` such as in:

```json
{
  "name": "devel",
  "type": "flannel",
  "delegate": {
    "ipam": {
      "routes": [
        { "dst": "0.0.0.0/0" }
      ]
    }
  }
}
```

The config above produces the error below:

```
Nov 21 16:01:54 kato-1.cell-1.dc-1.kato bash[3085]: E1121 16:01:54.067776  3105 slave.cpp:4520] Termination of executor 'tva_postgres.cfa3d65d-b003-11e6-8ee5-66d8fdff9eef' of framework 9c83f6d7-a2ba-4d36-8a0b-0ed560748792-0000 failed: Failed to clean up an isolator when destroying container: The CNI plugin '/var/lib/mesos/cni-plugins/flannel' failed to detach container f787f52a-e64d-4ed2-9cad-a4929ea53beb from CNI network 'devel': stdout='{
Nov 21 16:01:54 kato-1.cell-1.dc-1.kato bash[3085]:     "code": 100,
Nov 21 16:01:54 kato-1.cell-1.dc-1.kato bash[3085]:     "msg": "open /var/lib/cni/flannel/f787f52a-e64d-4ed2-9cad-a4929ea53beb: no such file or directory"
Nov 21 16:01:54 kato-1.cell-1.dc-1.kato bash[3085]: }', stderr=''
```

@squeed suggested (via Slack) that we should merge, instead of blocking.

> For Mesos, the executors launched as containers need to register with the Agent in order for a task to be successfully launched. Hence, it is imperative that the Agent IP is reachable from the container IP and vice versa.

I guess my Mesos agent is not reachable via the flannel routes, but this needs to be confirmed.

**Comment by squeed** [comment]
I don't see the use case for this. When we were first chatting in slack, it was not clear that you were simply trying to add the default route to the Flannel delegate, which is not necessary.

If you have a use case where you need to add a non-default route to the Flannel interface, can you add that and reopen this issue?
