### ISSUE TITLE
CNI + flannel with multiple interfaces

### ISSUE THREAD

**Issue by TerraTech** [containernetworking/cni#337]
Running on: CoreOS-1185.2.0 and quay.io/coreos/hyperkube:v1.4.6_coreos.0
Container runtime is: rkt

I am not sure if this is a CNI or flannel issue, but I sure could use a second set of eyes to look at this.

I added a new minion (KVM based) and decided to add a 2nd interface (eth1) that taps into a new storage network.  I mostly wanted to drop the storage VLAN that was sitting on eth0 as adding interfaces to a VM is cheap.  This is when I started to notice POD networking problems and began to dig further.
```
core-minion15 ~ # ip li ls
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:ca:70:81 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:eb:33:62 brd ff:ff:ff:ff:ff:ff
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 86:a0:82:a8:d0:27 brd ff:ff:ff:ff:ff:ff
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0a:58:0a:0b:69:01 brd ff:ff:ff:ff:ff:ff
6: veth87809580@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP mode DEFAULT group default
    link/ether 82:8e:a6:ad:59:f9 brd ff:ff:ff:ff:ff:ff
7: vetha2d5da5a@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP mode DEFAULT group default
    link/ether 56:73:64:14:f2:37 brd ff:ff:ff:ff:ff:ff

core-minion15 ~ # ip -d li ls dev cni0
5: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0a:58:0a:0b:69:01 brd ff:ff:ff:ff:ff:ff promiscuity 0
    bridge forward_delay 1500 hello_time 200 max_age 2000 addrgenmode eui64

core-minion15 ~ # bridge -d link
6: veth87809580 state UP @eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 master cni0 state forwarding priority 32 cost 2
    hairpin on guard off root_block off fastleave off learning on flood on
7: vetha2d5da5a state UP @eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 master cni0 state forwarding priority 32 cost 2
    hairpin on guard off root_block off fastleave off learning on flood on
```
Of interest:  veth87809580@**eth1**
which is restricted to the storage network and cannot communicate with the kubernetes network.

At this point, I though it might have been flannel, so I added '-iface=eth0' and rebooted.
```sh
# ps fxa | grep flanneld
 1090 ?        Ssl    0:00 /opt/bin/flanneld -ip-masq=true -iface=eth0
```
That did not fix the problem so I dug a little deeper and tried to add "master: eth0" and reboot:  /etc/kubernetes/cni/net.d/10-flannel.conf
```json
{
    "name": "podnet",
    "type": "flannel",
    "delegate": {
        "master": "eth0",
        "isDefaultGateway": true,
        "hairpinMode": true
    }
}
```
In the end, nothing I have tried worked and I am not sure how to force the veth interface to use eth0 instead.

My desired result is:  veth87809580@**eth0**

Am I missing a configuration setting somewhere other than what I've tried above?

**Comment by philips** [comment]
This might be related to some of the fixes we did to the leases in flannel v0.7.0. Which version are you using?

cc @tomdee

**Comment by TerraTech** [comment]
@philips sorry, I missed the email notice on this.  I'm running quay.io/coreos/flannel:v0.6.2

**Comment by tomdee** [comment]
I think this is a CNI issue. It's the bridge plugin that configures the veth so that's the best place to start looking.

**Comment by squeed** [comment]
The `@eth1` is the name of the interface inside the container - so nothing to worry about.
Closing this; feel free to reopen if needed.
