### ISSUE TITLE
Support building CNI on different architectures.

### ISSUE THREAD

**Issue by mbruzek** [containernetworking/cni#347]
I get a build error when trying to build the CNI binaries for different architectures.
```
+ docker run --rm -e GOOS=linux -e GOARCH=arm64 -v /var/lib/jenkins/jobs/kubernetes-build-resources/workspace/build-cni:/build-cni golang /bin/bash -c 'cd /build-cni && ./build && chown -R 0:0 /build-cni'
Building API
Building reference CLI
go install: cannot install cross-compiled binaries when GOBIN is set
```
The problem seems to be related to GOBIN being set. This works ok for building amd64 on amd64 but when trying to build the arm64 architecture from amd64 the build fails because GOBIN is set. Can we set something that would allow this to cross compile?

**Comment by mbruzek** [comment]
I should point out we were using the v0.3 branch and specifically this line: https://github.com/containernetworking/cni/blob/v0.3/build#L13

I don't see GOBIN in the `build` file on master. I will re-test with master and report back.

**Comment by cyphar** [comment]
Currently building (not through cross-compliation) on `aarch64` and `ppc64le` is broken:

* https://build.opensuse.org/package/live_build_log/home:cyphar:containers/cni/openSUSE_Tumbleweed/ppc64le
* https://build.opensuse.org/package/live_build_log/home:cyphar:containers/cni/openSUSE_Tumbleweed/aarch64

**Comment by tomdee** [comment]
It's working fine using this script - https://github.com/containernetworking/cni/blob/master/scripts/release-with-rkt.sh

**Comment by vielmetti** [comment]
I see that the release has binaries for multiple architectures. Is this issue still relevant? It's been a while.

**Comment by rosenhouse** [comment]
Yup.  Plugins have migrated to [`containernetworking/plugins`](https://github.com/containernetworking/plugins).  We shouldn't even be cutting binaries releases from here anymore, since the only remaining code is just the library and `cnitool`.
