### ISSUE TITLE
Should CNI plugins checkpoint information for DEL?

### ISSUE THREAD

**Issue by freehan** [containernetworking/cni#353]
Currently, CNI spec does not require plugins to checkpoint any information and many CNI plugins are stateless. Even if a CNI plugin is stateful, there is no CNI GET/STATUS or LIST operation to retrieve information. This implies that the caller (runtime) has to maintain states (netns, id, network configs) for clean up. However, not all information are needed for clean up. 

A few options for CNI checkpoint:
1) Do not require checkpoint in CNI spec (Current). Let the individual plugin determine its own behavior. However, in order to be compatible with more CNI plugins, the runtime has to assume the worst, hence maintain all information for DEL.
2) Require CNI plugins to take limited information for DEL. "Limited information" can be CONTAINERID+NetConfig or other combinations. This implies CNI plugins need to checkpoint the rest of necessary information for DEL.
3) Add LIST and STATUS/GET operation into CNI spec. These allows the runtime to be stateless wrt CNI configs. 

I prefer opt 2 as it balanced the responsibility between runtime and CNI. But need an agreement on the required information for DEL. I feel like combination of CONTAINERID and Network Config should be good enough. `host-local` ipam is doing this already. 

related: 
https://github.com/containernetworking/cni/issues/351#issuecomment-272498458 
https://github.com/containernetworking/cni/issues/351#issuecomment-272559099
https://github.com/containernetworking/cni/issues/309 
https://github.com/containernetworking/cni/issues/338

**Comment by freehan** [comment]
@containernetworking/cni-maintainers

**Comment by freehan** [comment]
@dcbw  @tomdee  @squeed

**Comment by tomdee** [comment]
I like option 2, but what about CNI_NETNS, CNI_IFNAME and CNI_PATH? Is it really just CNI_ARGS that you're excluding? What about any "args" passed in through the network config JSON?

**Comment by thockin** [comment]
If we're really looking at (2) why not go all the way and pass nothing but the ID?  What principle decides which information is passed vs what is not?

**Comment by rosenhouse** [comment]
Out of curiosity, what is the pain that you're experiencing that leads to this question?

You mentioned "netns, id, network configs" as things the runtime has to track.  Which of these (or something else?) is burdensome to track?   If we follow @thockin's suggestion and only require ID, does that meaningfully ease the burden on the runtime, compared to the other data?

**Comment by freehan** [comment]
> what is the pain that you're experiencing that leads to this question?

This has been brought up by CNI plugin and runtime writers in various places. Either CNI plugin need to be smart enough to maintain states(e.g. Calico), or runtimes have to do it (e.g. https://github.com/kubernetes/community/pull/255)

> You mentioned "netns, id, network configs" as things the runtime has to track. Which of these (or something else?) is burdensome to track? 

Parameters like netns requires the existence of container. If the container is stopped/deleted or runtime crashed, these information may be lost. Hence leaving dangling setup created by CNI plugin.

In addition, since CNI does not support UPDATE, this implies that CNI configs will stay the same from ADD til DEL. I would argue that at configs should not be passed at deletion time. Only a reference, like ID.

> If we follow @thockin's suggestion and only require ID, does that meaningfully ease the burden on the runtime, compared to the other data? 

If so, that will be great.

**Comment by freehan** [comment]
Probably need "cniVersion", "name" and "type" from the network config plus ID at least.

Otherwise, libcni need to go thru all plugins.

**Comment by rosenhouse** [comment]
So you're suggesting that the spec be updated so that the runtime only needs to provide the following to the plugin:

- CNI_CONTAINERID
- CNI_PATH
- `cniVersion`, `name` and `type` from the NetConfig

But if the runtime is bothering to track all of that, is it that much worse for the runtime to also track the rest of the environment variables and NetConfig?

> Parameters like netns requires the existence of container. If the container is stopped/deleted or runtime crashed, these information may be lost.

If the concern is that the netns has disappeared before DEL is called, then maybe we can instead stipulate that on DEL, the `CNI_NETNS` may point to a nonexistent path, and that plugins should be robust against that possibility, e.g. #309.

**Comment by squeed** [comment]
I'm uncomfortable with making this part of the spec. I think a checkpointing feature as part of libcni makes more sense.

**Comment by thockin** [comment]
If it is not part of the spec, then runtimes must do it.  All I want is a
clear statement of boundary.  To me, it feels cleaner overall for plugins
to own this, since they know best what they need, but I don't care *that*
much.  If we don't make it part of the spec, we should make it very clear
that runtimes must provide this info.

**Comment by freehan** [comment]
>- CNI_CONTAINERID
>- CNI_PATH
>- cniVersion, name and type from the NetConfig
>But if the runtime is bothering to track all of that already, is it that much worse for the runtime to also track the rest of the environment variables and NetConfig?

@rosenhouse These are the most runtime relevant information. What container exsited? (CNI_CONTAINERID) What/Where CNI plugin was invoked? (name, type, cniVersion, CNI_PATH. These usually comes as part of runtime configs). 

The rest is either CNI plugin specific or requires the existence of container (NetNS).

>If the concern is that the netns has disappeared before DEL is called, then maybe we can instead stipulate that on DEL, the CNI_NETNS may point to a nonexistent path, and that plugins should be robust against that possibility, e.g. #309.

NETNS is not the only concern. As we push more stuff into network configs, it becomes more and more dynamic. Multiple containers joining the same network may have very different network configs. (e.g. Port-Forwarding, Traffic Shaping). That is more burden on runtime to track these information to comply with CNI. However, not all information are needed for DEL, while individual plugin knows what is needed.

**Comment by rosenhouse** [comment]
What if `libcni` provided two extra functions, e.g. something like 

```go
SerializeConfs(net *NetworkConfigList, rt *RuntimeConf) ([]byte, error) { ... }
DeserializeConfs(serializedConf []byte) (*NetworkConfigList, *RuntimeConf, error) { ... }
```

(the implementation could be a straightforward JSON marshaling of the data)

Then runtimes would be responsible for storing those `byte`s wherever they like, and deserializing before calling `DEL`.

Does that address the need?  Or am I missing something?

**Comment by freehan** [comment]
This introduce lots of overhead though. Many fields are duplicated across containers.

**Comment by dcbw** [comment]
libcni caches the ADD config and result and passes the REsult into DEL now. If we find more things that libcni can checkpoint we can add those.
