### ISSUE TITLE
skel.PluginMain calls os.Exit instead of returning an error, preventing graceful shutdown

### ISSUE THREAD

**Issue by ofiliz** [containernetworking/cni#354]
CNI plugins that access state outside the immediate process (such as communicating with external processes, accessing shared resources, etc.) have to gracefully release those resources on exit. However, skel.PluginMain calls os.Exit directly on behalf of the plugin any time the ADD or DEL handler returns an error. This prevents the plugin from doing any graceful shutdown.

My understanding is the packages under cni.pkg are libraries, and libraries should not just kill the process in which they are loaded. They should return an error and leave it up to the caller to decide how to handle that error.

One could of course call a general cleanup function directly from inside the ADD and DEL handlers at every failure point, but that results in duplicate code and does not result in an elegant design.

What is the recommended way of doing graceful cleanup and shutdown?
Should we add an alternative PluginMain that returns an error instead of abruptly exiting?

**Comment by rosenhouse** [comment]
@ofiliz  💯 👍   Thanks for bringing this up, really good point.  I've opened #355 to address this.  Your comments there would be appreciated.

**Comment by ofiliz** [comment]
Thanks. I had coded a change as well, but wanted to confirm before submitting a PR.

**Comment by rosenhouse** [comment]
@ofiliz PR is merged, give it a whirl.

**Comment by ofiliz** [comment]
@rosenhouse Yes, works as expected.
