### ISSUE TITLE
CNI on Windows

### ISSUE THREAD

**Issue by ofiliz** [containernetworking/cni#357]
Hello,

We are interested in making CNI work on Windows. The primary scenario of interest is to enable Kubernetes on Windows use CNI to configure networking for Windows Containers.

Please note that the goal is to make the CNI interface and framework (libcni), and NOT the individual network plugins (such as ipvlan), to work on Windows. Although Linux and Windows use similar concepts for container networking (like network namespaces, bridges, etc.), the corresponding operating system APIs are obviously not compatible. Hence implementations of a particular network plugin type will differ. But the way CNI interfaces with plugins (such as passing input via environment variables, plugin invocation, network configuration files passed via stdin, etc.) are OS-agnostic and do work on Windows.

Also, most IPAM plugins do not make OS-specific calls, hence should either directly work or can be made to work on Windows with minor modifications.

To that end, I have a few PRs to address minor differences in Windows. Note these PRs are not just for Windows: they improve quality and also make CNI more compatible with other platforms. I am opening this issue to get the community's feedback and track the changes.

Thanks!

**Comment by ofiliz** [comment]
issue #358 PR #359

**Comment by rosenhouse** [comment]
Both PRs have been merged.  Can we close this?
