### ISSUE TITLE
Add Open vSwitch support

### ISSUE THREAD

**Issue by takaomag** [containernetworking/cni#36]
I think it would be nice if appc supports OVS. Is there any plan to support OVS?

**Comment by eyakubovich** [comment]
Not at the moment but I agree that it would be desirable.

**Comment by nstott** [comment]
the example configs at https://github.com/appc/cni/blob/master/SPEC.md#example-configurations seem to reference ovs, is this just theoretical?

**Comment by eyakubovich** [comment]
Just theoretical for now.

**Comment by resouer** [comment]
I think this one is a implementation.

**Comment by bboreham** [comment]
Also another one at https://github.com/John-Lin/linen-cni.  Considering this suggestion fulfilled, thanks to the community!
