### ISSUE TITLE
Netconf definition is missing Routes field

### ISSUE THREAD

**Issue by jojimt** [containernetworking/cni#362]
Looking at the definition of Netconf(https://github.com/containernetworking/cni/blob/master/pkg/types/types.go#L59), I see that all fields specified by https://github.com/containernetworking/cni/blob/master/SPEC.md (Network Configuration) are included here, **except** the **IPAM.Routes** field. Is there a specific reason for omitting it?

ping @rosenhouse @dcbw

**Comment by dcbw** [comment]
@jojimt this part of SPEC.md is actually in error.  The fields in the NetConf 'ipam' member are not specified, except the 'type' field which says which IPAM plugin to run.  The IPAM plugin itself handles any additional configuraiton inside the 'ipam' block of the NetConf.  The reference host-local plugin *does* accept a "Routes" field, which is probably where the confusion lies.

The spec should certainly get fixed to remove this for now.  I know there's some existing convention to be able to specify some IPAM details (like routes) and that should probably go in the new CONVENTIONS.md.

@rosenhouse @tomdee @steveeJ given that nothing in IPAM besides 'type' is really specified, how should we handle this?

**Comment by squeed** [comment]
For the specific case of setting static routes inside the container, this seems like a perfect opportunity for a plugin :-).
