### ISSUE TITLE
using 'args' instead of 'CNI_ARGS' for IP field in IPAM config

### ISSUE THREAD

**Issue by tomdee** [containernetworking/cni#367]
As per the conventions doc https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md, IPAM plugins can be asked to use a specific IP address by using `IP=<ip>` in the `CNI_ARGS` environment variable. 

Since using `CNI_ARGS` is deprecated, I suggest that we document that IP address preferences can be passed to IPAM plugins by using a field in args. This would allow for a list of IP addresses and potentially splitting IPv4 and IPv6.

WDPT?

**Comment by asridharan** [comment]
@tomdee 👍

**Comment by prateekgogia** [comment]
@tomdee I was trying out this option to set ip=<ip value> in args field passed to host-local IPAM config. Looks like host-local plugin ignores this field. Here is the small tweak I made to default conf file (added args option):

```
cat /etc/cni/net.d/10-mynet.conf
{
    "cniVersion": "0.2.0",
    "name": "mynet1",
    "type": "bridge",
    "bridge": "cni0",
    "isGateway": true,
    "ipMasq": true,
    "ipam": {
        "type": "host-local",
        "subnet": "10.11.0.0/16",
        "routes": [
            { "dst": "0.0.0.0/0" }
        ],
	**"args":
	{
	    "ip": "10.11.0.22"
	}**
    }
}

CNI_PATH=$CNI_PATH ./docker-run.sh --rm busybox:latest ifconfig
eth0      Link encap:Ethernet  HWaddr 0A:58:0A:0B:00:07
          inet addr:**10.11.0.7**  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::dcc3:e7ff:fe50:1a70/64 Scope:Link

```
The network created doesn't has the IP I have specified in args, it is still getting the next free IP in the subnet range. I just wanted to confirm is this a bug in host-local IPAM plugin or I am doing something wrong.

**Comment by rosenhouse** [comment]
@prateekgogia Right.  Two things need to happen.  

1. Document the preference for `args` in NetConf
2. Update the plugins in this repo to behave according to that documentation

**Comment by squeed** [comment]
I'm not exactly sure when this happened, but it did!
