### ISSUE TITLE
generate hwaddr (mac address) from an IPv6 address

### ISSUE THREAD

**Issue by danehans** [containernetworking/cni#370]
Currently, an IPv4 address is needed to generate a MAC address. The [GenerateHardwareAddr4 function](https://github.com/containernetworking/cni/blob/master/pkg/utils/hwaddr/hwaddr.go#L48-L49) should be updated or replicated to support IPv6 addresses for generating a  mac address of a container.

**Comment by bboreham** [comment]
I think #448 would obviate this issue.

**Comment by dcbw** [comment]
https://github.com/containernetworking/plugins/pull/16 has been committed and obviates this issue.
