### ISSUE TITLE
Where is the template?

### ISSUE THREAD

**Issue by fkautz** [containernetworking/cni#392]
The README.md states there is a template for making a new CNI plugin, but does not state where in the repository the template is. The repository is large enough now that we should just link to the template.

**Comment by bboreham** [comment]
I asked the same question when I first looked at CNI, and was pointed at the `skel` package.

Personally I wouldn't call that a template, more a helper library.

**Comment by squeed** [comment]
I've added a template [here](https://github.com/containernetworking/plugins/tree/master/plugins/sample), check it out.

**Comment by squeed** [comment]
Yup, that's the official template; closing this.
