### ISSUE TITLE
Vendoring cni and netlink

### ISSUE THREAD

**Issue by jaydunk** [containernetworking/cni#395]
We're writing a CNI plugin and running into a few issues around vendoring `containernetworking/cni` and netlink.

First is that running the normal `go build` fails due to multiple definitions of `vishvananda/netlink`:
```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-088250716/000002.o: In function `_cgo_f36fc5609ae4_C2func_load_simple_bpf':
veth/go/src/github.com/cloudfoundry-incubator/silk/vendor/github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink/bpf_linux.go:77: multiple definition of `_cgo_f36fc5609ae4_C2func_load_simple_bpf'
veth/tmp/go-link-088250716/000000.o:/go/src/github.com/cloudfoundry-incubator/silk/vendor/github.com/vishvananda/netlink/bpf_linux.go:77: first defined here
```

We are able to work around this by adding `-ldflags="-extldflags=-Wl,--allow-multiple-definition"` to our build commands.

A bigger issue comes up when trying to use the existing cni libraries while also vendoring in netlink. I have a function for creating a veth pair and returns the pair back to the caller. I would like to leverage the `SetupVeth` function in `pkg/ip`. For example:

```
	var hostVeth, containerVeth netlink.Link
	err = containerNS.Do(func(_ ns.NetNS) error {
		hostLink, containerLink, err := ip.SetupVeth(ifname, mtu, hostNS)
		if err != nil {
			return err
		}
		return nil
	})

```

This fails to compile since `hostVeth` and `containerVeth` are of type `netlink.Link` as defined in `vendor/github.com/vishvananda/netlink` but `SetupVeth` returns `netlink.Link` as defined in `vendor/github.com/containernetworking/cni/vendor/github.com/vishvananda/netlink`.

cc: @rosenhouse

**Comment by bboreham** [comment]
You really have to use a vendoring technique that flattens dependencies such that there is only one copy of each library, and they're all at top level. 

Tools like `dep`, `gvt` and `glide` will do this for you. 

Ideally no library repo would vendor any dependencies, but this repo is both a library and a source of binaries.

**Comment by dcbw** [comment]
I have no real problem with the actual PR (now that net.Interace is used) but this does bring up the question of what packages in CNI are private and which are public API.  Do we expect people to vendor in parts of CNI just to use one single function like SetupVeth?  (not saying that's the case here, just posing a question)

**Comment by rosenhouse** [comment]
Exactly.

I don't know what the right answer is, but here's one data point: For Cloud Foundry, we're building a new CNI plugin and finding that we would really like to be able to re-use some of these library functions used by the plugins in this repo.   (`SetupVeth` is one, we expect to want to use more).   But that re-use is difficult without changes like #396.

Ideally, the core CNI plugins would be extracted out of this repo and into a separate one, which vendors this repo.  Then we'd be eating our own dogfood.

**Comment by rosenhouse** [comment]
The [reference CNI plugins are now in a separate repo](https://github.com/containernetworking/plugins).  If this problem still exists, it's now in that repo!  Closing...
