### ISSUE TITLE
How to i use the CNI Framework in Rancher ?

### ISSUE THREAD

**Issue by asdarunasd** [containernetworking/cni#397]
I have set up rancher and as in rancher when we add a container .. The current networking approach introduces a second IP address for each of the containers; this introduces some difficulties, 

I have read in some article that we can create an interface with CNI framework to expose only one ip from the container through rancher..

How can i do this? I am very new to this? So please help

**Comment by bboreham** [comment]
@asdarunasd CNI is a very general mechanism that can be used by many platforms.  For information on how to use CNI within the Rancher platform, you need to ask the Rancher folks.

Here are some links to get started: 

http://docs.rancher.com/rancher/v1.3/en/rancher-services/networking/
http://rancher.com/tag/cni/
http://rancher.com/support

**Comment by leodotcloud** [comment]
@asdarunasd Rancher has migrated to CNI framework starting 1.2 release (currently 1.5.1). The behavior (issue) that you have mentioned is true only for pre-1.2. Please feel free to join Rancher Users [Slack](https://rancher-users.slack.com) channel for more questions. As Bryan pointed out, this is not the right place to ask specific questions regarding Rancher.
