### ISSUE TITLE
bridge plugin should allow bridging a host iface

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#40]
As a convenience feature, bridge plugin should have an ability to connect host interface to the bridge (when the bridge is created).

(moved from https://github.com/coreos/rkt/issues/477)

**Comment by eyakubovich** [comment]
@steveeJ I wasn't thinking of transferring any attributes. This was for the cases where somebody wants to use a dedicated host interface for containers. Then this interface would not have an IP, it would just be bridged. It can be done now with the user first creating a bridge and then attaching the host interface to it. But since the "bridge" plugin can create the bridge, it might as well also have the ability to plug the host interface into it.

**Comment by steveeJ** [comment]
Since plugins have moved to a separate repository this issue is now misplaced.
Judging by the inactivity there's not much request for this feature either, therefore closing should be fine.
