### ISSUE TITLE
macvlan cross host communication problem

### ISSUE THREAD

**Issue by shouhong** [containernetworking/cni#405]
I used Kubernetes + macvlan + host-local. The pods running on the same K8S node can communicate with each other. But pods running on different K8S node cannot communicate with each other. How to enable macvlan for cross host communication? Thanks!

I have 3 K8S nodes and the CNI configurations are:

Node1:
`{
    "name": "mynet",
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/23",
        "rangeStart": "192.168.0.190",
        "rangeEnd": "192.168.0.195",
        "gateway": "192.168.1.1"
    }
}`

Node2:
`{
    "name": "mynet",
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/23",
        "rangeStart": "192.168.0.196",
        "rangeEnd": "192.168.0.201",
        "gateway": "192.168.1.1"
    }
}`

Node3:
`{
    "name": "mynet",
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/23",
        "rangeStart": "192.168.0.202",
        "rangeEnd": "192.168.0.207",
        "gateway": "192.168.1.1"
    }
}`

**Comment by squeed** [comment]
What sort of networking environment are you using? Are the pods able to reach the broader internet / gateway?

Some L2 "switches", especially those in cloud environments, have restrictions on the sort of traffic is allowed. Often they have restrictions such as one MAC per host.

**Comment by shouhong** [comment]
The host machines are VMs running on VMware ESX serve and the network is VM network.

**Comment by squeed** [comment]
Then it is likely that the vmware network restricts the MACs available per interface. I'm afraid I have no experience with it.

**Comment by derit** [comment]
same issue, when i test with docker macvlan it work, with cni macvlan not work 😞

**Comment by bboreham** [comment]
@derit the macvlan plugin has moved to https://github.com/containernetworking/plugins

If you want someone to consider your issue, please give details - what versions, what environment, what the symptoms are, etc.
