### ISSUE TITLE
Bridge plugin needs support for IPv6 addresses

### ISSUE THREAD

**Issue by leblancd** [containernetworking/cni#415]
Support needs to be added to the bridge plugin in order for it to support dual-stack and
IPv6-only network configurations.

Changes to the bridge plugin will also depend upon changes proposed in PR #279 and PR #394
in order to exercise/test IPv6 functionality.

**Comment by rosenhouse** [comment]
Does https://github.com/containernetworking/plugins/pull/10 replace this one?

**Comment by leblancd** [comment]
@rosenhouse : Yes, [containernetworking/plugins#10](https://github.com/containernetworking/plugins/pull/10) replaces [containernetworking/cni#416](https://github.com/containernetworking/cni/pull/416). I don't know if I need to create a new issue in containernetworking/plugins for the new PR?

**Comment by rosenhouse** [comment]
Nah, I'd say that opening a new issue would be superfluous.  Closing this...
