### ISSUE TITLE
CNI needs a logo

### ISSUE THREAD

**Issue by caniszczyk** [containernetworking/cni#426]
I think CNI needs a logo and the Linux Foundation would like to help.

Are the CNI maintainers game?

**Comment by philips** [comment]
Sure, I think a little brand recognition would be good.

**Comment by caniszczyk** [comment]
[CNI_LogoPresentation_v1.pdf](https://github.com/containernetworking/cni/files/910376/CNI_LogoPresentation_v1.pdf)

Here are some concepts, any direction you like @philips and CNI maintainers? I'm kind of digging the third one but it's all up to you ;)

**Comment by bboreham** [comment]
Thanks @caniszczyk !  I agree CNI could use a logo.

Some instant reactions, though I have to warn you I'm terrible at visual design :grimacing: :
* I like the first one the most, although it did read a bit like a 'K' to begin with.  As I look back, it's more like a 'C'
* Second one seems to imply San Francisco.  Although I love San Francisco as a city, there's no particular association between CNI and San Francisco.
* Third one just seems a bit nebulous.

**Comment by caniszczyk** [comment]
@bboreham any idea how we can get the other CNI containers to comment?

would love to iterate and come to a decision here ;)

**Comment by tomdee** [comment]
+1 to having a logo.

None of these designs particularly grab me, but I'd be happy with any of them. My instant thoughts
1. I probably like this the most too, but the color scheme didn't _feel_ right to me. I'm not sure about the yellow and grey. 
2. Agree on the point about SF
3. This reminds me of some existing cloud company, but I'm not sure who. Maybe mesosphere?

**Comment by hwinkel** [comment]
Just my two cents about the logo:

- Font of 1st Option
- Color of 3rd option
- Logo a bit between option 1 and 3 or maybe just option 3

**Comment by squeed** [comment]
Hi, thanks for this!

My first thought is that I like the color scheme and general shape of the first logo, but I like the implication of "connectedness" that the second logo implies.

If I close my eyes, i somehow see the CNI logo being a play on a subway diagram. Note: I am literally the opposite of a trained visual designer. I also play too much Mini Metro.

**Comment by caniszczyk** [comment]
Thanks for the feedback everyone, we will circle back with the LF Design team and produce a couple set of new options

**Comment by shawnpreissner** [comment]
Hi all - new set attached. Please rank your top two...thanks!
[CNI_LogoPresentation_v2.pdf](https://github.com/containernetworking/cni/files/959532/CNI_LogoPresentation_v2.pdf)

**Comment by caniszczyk** [comment]
And by top 2, @shawnpreissner top 1 ;)

cc: @bboreham and others

**Comment by cmluciano** [comment]
The subway with the purple hue in the background is sweet. The first logo reminds me of something from the cloud container space.

**Comment by caniszczyk** [comment]
anyone else in CNI dev land? @philips ?

**Comment by shawnpreissner** [comment]
Thanks for the feedback @cmluciano 
Attaching a final additional stylistic text option (Concept 4) to be included in your vote.

Would love to hear your preference @philips @bboreham @tomdee @hwinkel @squeed 
[CNI_LogoPresentations_v3.pdf](https://github.com/containernetworking/cni/files/967946/CNI_LogoPresentations_v3.pdf)

**Comment by jonboulle** [comment]
I think 3'd be my preference followed by 1

**Comment by philips** [comment]
I think 3'd be my preference followed by 1.

I don't "get" any of them but abstract lines seems fine.

**Comment by squeed** [comment]
I like 3 a lot. Wonderful!

**Comment by bboreham** [comment]
I like 1, but wonder if it's just a bit too Escher.  Or if my eyes need testing.
2 too much like a train.
3 is nice - bit like a C, bit like a ring-binder
I also like 4.  Too obvious maybe?

If I was to put them in order, 3, 4, 1, 2.

**Comment by philips** [comment]
Seems like 3, ship it

**Comment by caniszczyk** [comment]
Thanks @philips and all! We'll send the artifacts your way in a bit and I'll send a PR to the repo

**Comment by caniszczyk** [comment]
[CNI_LogoSet.zip](https://github.com/containernetworking/cni/files/979745/CNI_LogoSet.zip)

Here's the full logo! @philips do you want to create a logo/artwork repo or put this somewhere in the main repo? Thanks

**Comment by tomdee** [comment]
I'm adding this logo to the containernetworking slack

**Comment by caniszczyk** [comment]
Logo exists now! https://github.com/containernetworking/cni/pull/452

https://github.com/cncf/artwork/tree/master/cni
