### ISSUE TITLE
Mistake in history of "args"

### ISSUE THREAD

**Issue by MikeSpreitzer** [containernetworking/cni#429]
https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#args-in-network-config says the `args` field was introduced in spec version 0.1.0.  As best I can tell, it was actually introduced in spec version 0.2.  The "Spec changes" listed for https://github.com/containernetworking/cni/releases/tag/v0.4.0, which says it corresponds to spec version 0.2.0, includes 'introduce "args" field and new error code'.

**Comment by cmluciano** [comment]
Should the CONVENTIONS be updated to mention this?

**Comment by bboreham** [comment]
Hmm, this could get confusing. The change was in commit 7b381a1af2c6120caf9a45a1b16eb86a25b165e5 which was made while the file was labelled 0.1.0.  Some examples in [SPEC.md](https://github.com/containernetworking/cni/blob/7b381a1af2c6120caf9a45a1b16eb86a25b165e5/SPEC.md#example-configurations) at that time show `"cniVersion": "0.1.0",` together with `args`.

However I think we can argue that readers of the spec should only consider tagged releases "official", and the first tagged release with `args` showed 0.2.0.  I made a PR #467
