### ISSUE TITLE
Add VERSION command to cnitool plugin

### ISSUE THREAD

**Issue by micahhausler** [containernetworking/cni#436]
After reading the spec, it seems like `cnitool` should also handle the `version` command. I'd be happy to add this.

**Comment by rosenhouse** [comment]
@micahhausler as folks said in #437, the `cnitool` is not itself a plugin, but instead drives plugins.  it might be useful for it to learn how to ask plugins for their version.  Feel free to open a PR for that.  In the meantime, I'm going to close this issue.
