### ISSUE TITLE
CNI blocks forever on subnets conflict

### ISSUE THREAD

**Issue by feiskyer** [containernetworking/cni#442]
Bridge plugin of master branch is blocking forever on travis (e.g. [here](https://travis-ci.org/feiskyer/go-examples/jobs/225873245#L318), which is easily to be reproduced by 

```
sudo CNI_PATH=/opt/cni/bin NETCONFPATH=/etc/cni/net.d ./cnitool add net /var/run/netns/test
```

~~I think we should revert #439 temporally util the root cause is found.~~

Update: Confirmed it is because the subnet CIDR is conflict with travis's vm (10.10.0.0/16). By changing it to another subnet solved this problem.

cc/ @bboreham @dcbw @dnardo

**Comment by dnardo** [comment]
Interesting I'm not able to repro this on my machine:

→ sudo CNI_PATH=/opt/cni/bin NETCONFPATH=/etc/cni/net.d ./cnitool add net /var/run/netns/test                                                                                                   [21d9639]
{
    "ip4": {
        "ip": "10.10.0.3/16",
        "gateway": "10.10.0.1",
        "routes": [
            {
                "dst": "0.0.0.0/0",
                "gw": "10.10.0.1"
            }
        ]
    },
    "dns": {}
}%                                                                                                                                                                                                        

What does the CNI conf look like for the particular test that is hanging?

**Comment by feiskyer** [comment]
@dnardo The config is from [here](https://github.com/feiskyer/go-examples/blob/master/networking/cnitool/install-cni.sh#L28).

I can't reproduce this on my machine either, but it did block on travis. Maybe it is related with kernel versions.

**Comment by feiskyer** [comment]
Confirmed it is because the subnet CIDR is conflict with travis's vm (10.10.0.0/16). By changing it to another subnet solved this problem.

**Comment by bboreham** [comment]
So is that related to #439 or just a coincidence?

**Comment by feiskyer** [comment]
@bboreham Not related with #439. 

But should we consider this blocking as a bug of cni?

**Comment by bboreham** [comment]
Which file in this repo is causing the problem?

**Comment by feiskyer** [comment]
Not sure yet. Although it could be easily triggered on travis, I can't reproduce it on my machine.

**Comment by bboreham** [comment]
Surely if you pick the subnet for your test, that has nothing to do with CNI itself.  CNI's Travis tests are not failing.

**Comment by feiskyer** [comment]
Yep. I think it is not the issue of CNI. will close this issue.
