### ISSUE TITLE
ipvlan plugin did not work

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#45]
ipvlan did not work for @thockin. Ask him for details.

**Comment by steveeJ** [comment]
@thockin please provide details that allow me to reproduce the problem and track it down.

**Comment by eyakubovich** [comment]
Tested on latest Ubuntu (kernel 4.2.0-18) and it worked ok.

**Comment by thockin** [comment]
I have not had any time to test this further, I'll get back to it
eventually.

**Comment by f0** [comment]
tested ipvlan on coreos VERSION=835.7.0, does work

**Comment by rosenhouse** [comment]
This issue is very old.  If you're currently encountering issues with the ipvlan plugin, please open a new issue in the [plugins repository](https://github.com/containernetworking/plugins).
