### ISSUE TITLE
Publish additional hashes for releases

### ISSUE THREAD

**Issue by brianredbeard** [containernetworking/cni#468]
Publishing the SHA1 hashes is a great start.  Ideally publishing the SHA256 and SHA512 hashes would allow users to more confidently retrieve CNI releases and allow for easier upstream consumption - e.g.

[kubernetes/kubernetes:build/root/WORKSPACE#L89](https://github.com/kubernetes/kubernetes/blob/3837d9519190069c44a453c145869e1fced52f23/build/root/WORKSPACE#L89)
```
http_file(
    name = "kubernetes_cni",
    sha256 = "05ab3937bc68562e989dc143362ec4d4275262ba9f359338aed720fc914457a5",
    url = "https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz",
)
```

Other blockers (like the lack of all supported architectures) have now been resolved, thus this will be one more step in the right direction.

**Comment by tomdee** [comment]
I added sha256 and sha512 hashes - they will be included on the next release.
https://github.com/containernetworking/cni/pull/473/files#diff-0d28f82f2d1cc0deb12146b212778bc9R32
