### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by feiskyer** [containernetworking/cni#480]
@dcbw  When will cni publish its next release?

**Comment by tomdee** [comment]
We're planning to plan an RC on Wednesday potentially getting the final release out a week or two after that.

**Comment by rosenhouse** [comment]
A bit late, but v0.6.0-rc2 of [CNI](https://github.com/containernetworking/cni) and [Plugins](https://github.com/containernetworking/plugins) repository is now available.  Feedback welcome in IRC, Slack or email.
