### ISSUE TITLE
flannel: Allow for additional routes to be specified

### ISSUE THREAD

**Issue by awilliams** [containernetworking/cni#486]
I would like to use the flannel plugin and specify custom routes. As issue #333 outlined, it's not possible via the `delegate` field in the flannel CNI configuration file.

**Background:**
I would like to bring up a container with multiple network interfaces. For example:

* `eth0`: flannel interface, _not_ the default route.
* `eth1`: macvlan interface, default route.

The Kubernetes services are on `192.168.128.0/17`. 
Flannel internal network is on `192.168.0.0/17`. 

Relevant configurations:
```
$ cat /run/flannel/subnet.env
FLANNEL_NETWORK=192.168.0.0/17
FLANNEL_SUBNET=192.168.55.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false

$ cat /etc/cni/net.d/flannel.conf
{
  "name": "flannel",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": false
  }
}
```

The routes from within the container (with the eth1 routes x'd out):
```
$ ip route
default via 10.x.x.x dev eth1
10.x.x.x/29 dev eth1  proto kernel  scope link  src 10.x.x.x
192.168.0.0/17 via 192.168.55.1 dev eth0
192.168.55.0/24 dev eth0  proto kernel  scope link  src 192.168.55.96
```

I don't know of a way to setup the routes so that there's a route to the Kubernetes services via `eth0`. **As a result, the containers are unable to reach Kubernetes service endpoints.**

**Proposal:**

Allow for additional routes to be specified via the flannel configuration file (/etc/cni/net.d/flannel.conf). 

I prototyped a modified version of the flannel plugin, and was successfully able to add an additional route (relevant [flannel CNI plugin code](https://github.com/containernetworking/plugins/blob/v0.6.0-rc1/plugins/meta/flannel/flannel.go#L234-L237)). I'd be willing to submit a PR if accepted.

One option would be with a new optional field under `delegate`. Example:

```javascript
{
  "name": "flannel",
  "type": "flannel",
  "delegate": {
    "additionalRoutes": ["192.168.128.0/17"],   // optional array of CIDRs
    "isDefaultGateway": false
  }
}
```

Note: #337 looks like it might be related to the issue I describe above.

**Comment by awilliams** [comment]
Please advise if this isn't the correct place for this proposal.

**Comment by bboreham** [comment]
Flannel plugin has moved to https://github.com/containernetworking/plugins/
