### ISSUE TITLE
CNI v0.3 SPEC seems to represent incorrect result structure

### ISSUE THREAD

**Issue by asridharan** [containernetworking/cni#488]
The result section in CNI v0.3 and CNI v0.2 look identical , but 0.3.1 and 0.3.0 has a huge difference in their result structure. This doesn't make sense ??

**Comment by matthewdupre** [comment]
Do you mean this change? https://github.com/containernetworking/cni/pull/413

**Comment by dcbw** [comment]
@asridharan when you say "v0.3" do you mean the 0.3.0 specification?

Note that the spec and CNI release version are numbered differently...

**Comment by asridharan** [comment]
@dcbw  yeah I meant 0.3.0. Not sure if that corresponds to the v0.3.0 branch of the CNI repo:
https://github.com/containernetworking/cni/blob/v0.3/SPEC.md

That seems identical to:
https://github.com/containernetworking/cni/blob/v0.2/SPEC.md

Am I reading the version numbers incorrectly? If yes than how do I get the 0.3.0 spec and what do the branching and tags even mean at this point (given that `libcni` and CNI plugins have been split from this repo).

**Comment by matthewdupre** [comment]
The releases page is a good reference.  https://github.com/containernetworking/cni/releases

Each release's note says what the spec version of that release is.  Those branches seem very old - I'm not sure why they're still present?

**Comment by asridharan** [comment]
@matthewdupre again that page is conflating the libraries and the SPEC which is causing a lot of confusion. I would really like the SPEC.md to be version specific with the SPEC version appended to the name of the SPEC.md. So CNI 0.1 should be captured in SPECV0.1.md and so on...

The current state affairs is not very manageable and I am starting to get the feeling that apart from the maintainers no one else really understands the versioning. 

This needs to be fixed at the earliest.

**Comment by rosenhouse** [comment]
I've just pushed the following tags:
```
spec-v0.1.0 5c3c17164270150467498a32c71436c7cd5501be
spec-v0.2.0 530dd71e193012895ff7beee42cd64a02e1993da
spec-v0.3.0 4ce9b019aab51b28a32ff6549784a69f9b209fe4
spec-v0.3.1 137b4975ecab6e1f0c24c1e3c228a50a3cfba75e
```

I hope this helps people find the appropriate spec files.

**Comment by rosenhouse** [comment]
Ok, I've opened #495 to add these git tags to the spec.

Also, does anyone object if we **delete the branches** `v0.2` and `v0.3` which caused the original confusion?

**Comment by asridharan** [comment]
Thanks @rosenhouse !! Yeah deleting v0.2 and v0.3 sounds like a good idea to me. That is quite confusing.

**Comment by rosenhouse** [comment]
Ok, those branches have been deleted.  Closing this issue.
