### ISSUE TITLE
CNI 0.6.0 .deb absent from Ubuntu Xenial repository

### ISSUE THREAD

**Issue by RRAlex** [containernetworking/cni#503]
The repository used for CNI in debian format only has version up to 0.5.1:
`deb http://apt.kubernetes.io/ kubernetes-xenial main`

Was this a change of distribution model or simply a build step that was forgotten?
Cheers!

**Comment by feiskyer** [comment]
I think `http://apt.kubernetes.io/` is not managed by cni team. It should be managed by kubernetes team, which is planing to support CNI 0.6 in v1.9.

**Comment by bboreham** [comment]
CNI is independent of Kubernetes; I can confirm that the CNI project has no `deb` repository at this time.
