### ISSUE TITLE
Add ability to validate a CNI configuration to libcni

### ISSUE THREAD

**Issue by squeed** [containernetworking/cni#523]
It would be nice to have a function that took a CNI configuration and ensured it was reasonably executable:

- It compiles
- All the relevant plugins are on disk and executable
- They all support the correct cniVersion

We already have most of this code, we should just expose it as a public function.

**Comment by nmiculinic** [comment]
Is there some CLI to validate CNI config?

**Comment by squeed** [comment]
@nmiculinic no, but that would be a great addition to `cnitool`!
