### ISSUE TITLE
CNI should fail gracefully if the iptables rule doesnt exist

### ISSUE THREAD

**Issue by baude** [containernetworking/cni#539]
In cases where something has come in and nuked iptables' world (like firewalld reloading), and a subsequent CNI plugin is called, it should fail gracefully.  An issue on the libpod project has  nice description of this and I was asked to file an issue over here as well...

Link to original issue -> https://github.com/projectatomic/libpod/issues/348

**Comment by squeed** [comment]
A good idea. I've filed coreos/go-iptables#46 to get lay the groudwork for this.

**Comment by edsantiago** [comment]
I'm not sure if this is related, but this morning I saw one instance of:
```
# podman run --name foo fedora bash -c 'echo READY'
# podman stop --time=10 foo
4e74dd21eba5bb905402245f08dc23ed69aeaebe1798da7155e4ac7c9c8bc41d
`iptables -t filter -D FORWARD -s 10.88.0.119 ! -o 10.88.0.119 -j ACCEPT` failed: iptables: Bad rule (does a matching rule exist in that chain?).
Error deleting network: failed to Statfs "/var/run/netns/cni-cfd5c7c0-af45-70d3-3faa-ae7781860ee3": no such file or directory
Failed to tear down network namespace for container 4e74dd21eba5bb905402245f08dc23ed69aeaebe1798da7155e4ac7c9c8bc41d: failed to Statfs "/var/run/netns/cni-cfd5c7c0-af45-70d3-3faa-ae7781860ee3": no such file or directory
```
I've tried to reproduce it, under load and with repeated `firewall-cmd --reload`, and been unable to. I realize this is unhelpful; I'm filing anyway in case this helps someone find a pattern.

**Comment by squeed** [comment]
It looks like you're using the iptables-allow plugin? I bet it has the same bug.
