### ISSUE TITLE
Question: How should runtime pass the CNI version to plugin?

### ISSUE THREAD

**Issue by qianzhangxa** [containernetworking/cni#542]
In the [Parameters](https://github.com/containernetworking/cni/blob/master/SPEC.md#parameters) section of the spec, I see the first parameter `Version` is used to pass the CNI version from runtime to plugin, however in the [Network Configuration](https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration) section, I see the first field `cniVersion` is also used to pass the CNI version from runtime to plugin.

This makes me a bit confused, are they two different ways to pass CNI version from runtime to plugin? Or actually they refer to the same way?

**Comment by squeed** [comment]
Good question. The version in the passed json configuration is the only version. We should clean up the spec.

**Comment by qianzhangxa** [comment]
@squeed I have created a [PR](https://github.com/containernetworking/cni/pull/543) to fix it.
