### ISSUE TITLE
Document should describe how to add runtime convention in yaml

### ISSUE THREAD

**Issue by hainesc** [containernetworking/cni#544]
Hi, all

Maybe I mistaken something, but I can not find a way how to pass runtime information to the cni plugins through writing some code in yaml. I'd like to use host-local plugin and give a pod a special IP. I know the code below will return a special IP.
```shell
$ echo '{ "cniVersion": "0.3.1", "name": "examplenet", "ipam": { "type": "host-local", "ranges": [ [{"subnet": "10.2.2.0/24"}], [{"subnet": "2001:db8::/64"}]], ...  }, "ips": ["10.2.2.42", "2001:db8::5"] }' | CNI_COMMAND=ADD CNI_CONTAINERID=example ... ./host-local
```
But, What should be written in yaml if I'd like to get this?

**Comment by bboreham** [comment]
CNI defines an interface that a runtime can call; it does not define how to say that the runtime should make that call with specific parameters. 

Sounds like your question should be directed at the runtime.

**Comment by hainesc** [comment]
Thanks for your response. On the CNI side, it's a SPEC or interface only and on the other side, the kubernetes, or other runtime who calls the CNI, should call the plugins with specific parameters. So I will find the answer in kubernetes.

Thanks again!
