### ISSUE TITLE
Add skel plumbing for `--version`

### ISSUE THREAD

**Issue by squeed** [containernetworking/cni#547]
One oft-requested feature is the ability to know a plugin release version. This simple thing is slightly tricky because `skel` is essentially the main method.

So, at the very least, we should add a `--version` or `--about` string. Even better would be a clean ability to add arbitrary argument parsing through `skel` if its easy to do.

**Comment by dcbw** [comment]
Fixed in https://github.com/containernetworking/cni/pull/554
