### ISSUE TITLE
CNI spec does not address concurrent invocations of plugins

### ISSUE THREAD

**Issue by dcbw** [containernetworking/cni#563]
Does the CNI spec allow concurrent invocations of a plugin on the same network namespace?  Does it allow concurrent invocations of a plugin on different network namespaces?  Does it allow concurrent invocations at all?  Nothing is specified about it, so maybe want to solidify that.

One reason the question came up was with the multi-network spec; if you have multiple attachments to the same network, are those CNI plugins allowed to be executed in parallel?  In this case the interface name would be different between the two invocations, though the container ID and network name would be the same.  Also both invocations would be working in the same Linux network namespace.

@MikeSpreitzer @containernetworking/cni-maintainers @squeed

**Comment by jellonek** [comment]
Concurrent invocation in same network namespace (of the same plugin or several different) - will almost certainly lead to catastrophe (interface naming inside container ns). With different plugins (look on calico) there can be also assumption that e.g. there is no default route already configured in ns and if there is one already set - plugin will explode.

For different namespaces - spec does not specify that and it's up to plugin implementation at the moment.

IMO even if it's looking tempting to allow parallel invocation of plugins - there is no easy way to provide synchronization between them (e.g. for routing table, which can be manipulated by any of them) without adding a full bloated interface for that, probably including some rpc to caller. That's imo overkill.

That's one topic - but other is a specification of plugins behavior during sequential execution.
What if plugin wants to set default route, but there is one already set - which one should finally be used - one set by first, or replaced by second? (imo second option, as second plugin overwrites/tunes configuration made by first one). I don't have at the moment other examples, but maybe something similar can occur with iptables or brtables?

**Comment by bboreham** [comment]
Good question.  There was some discussion on the topic of resolving routing table decisions at https://github.com/docker/libnetwork/issues/939 (TL;DR: no resolution)

**Comment by dcbw** [comment]
So actually I lied and didn't read the spec closely enough, and it does mention parallelism.

`The container runtime must not invoke parallel operations for the same container, but is allowed to invoke parallel operations for different containers.`

So I guess the question is if we could relax this requirement for invocations of different uniqueness tuples but for the same container.

**Comment by jellonek** [comment]
That can lead to race condition between different plugins (or same with different configurations) during:
 * renaming interface in container netns to next ethX
 * adding default route

**Comment by squeed** [comment]
Yeah, I definitely would prefer to keep the spec as-is; linux is racy enough...
