### ISSUE TITLE
No timeout when  cni call  cni binary file.

### ISSUE THREAD

**Issue by liucimin** [containernetworking/cni#567]
**BUG REPORT**:

/kind bug

**What happened**:
Cni just use exec.Cmd to call the cni binary file.
In some cni plugin,such as contiv,the cni binary file may be locked and no return.
In some case, Such as in k8s,when kubelet first time call RunPodSandbox got a ctx timeout. the next time kubelet re-creates PodSandbox, it will always report this timeout.It because the kubelet ask a lock before call the cni plugin.

**Comment by nikopen** [comment]
https://github.com/containernetworking/cni/pull/568 got merged, this is resolved I presume?

**Comment by liucimin** [comment]
@nikopen  yes
