### ISSUE TITLE
Unable to parse error returned by CNI plugin

### ISSUE THREAD

**Issue by tamilmani1989** [containernetworking/cni#571]
Azure CNI is using the method provided by cnitypes package [https://github.com/containernetworking/cni/blob/master/pkg/types/current/types.go#L208](url)
to print error in stdout but still we are seeing the following error both in Linux and windows

`error while adding to cni network: netplugin failed but error parsing its diagnostic message "{\n \"cniVersion\": \"0.3.0\",\ n \"interfaces\": [\n {\n \"name\": \"eth0\"\n }\n ],\n \"dns\": {}\n}{\n \"code\": 100,\n \"msg\": \"Failed to allocate address: Failed to delegate: Failed to allocate address: No available addresses\"\n}": invalid character '{' after top-level value`
W0712 22:28:39.344476 2872 docker_sandbox.go:372] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "iis-1803-688b96c57b-rqlxs_def
ault":

**Comment by jellonek** [comment]
Could you provide a method to reproduce this error?

**Comment by dcbw** [comment]
@tamilmani1989 it looks wrong to me that the plugin returns *both* a result and an error?  If the plugin has an error, it should return only an error.

**Comment by tamilmani1989** [comment]
@dcbw Thanks for your response. Let me check and get back to you.

**Comment by tamilmani1989** [comment]
@dcbw  In case of error, we write result to stdout and return **nil, error** from this function `CallPlugin`

**Comment by tamilmani1989** [comment]
Ok I fixed it. We are not suppose to write result to stdout in case of error. Thanks guys!
