### ISSUE TITLE
CNI adds IPTables rules in backwards order

### ISSUE THREAD

**Issue by varunmar** [containernetworking/cni#577]
One issue this causes is that the HOSTPORT-DNAT rule chain is traversed before the SERVICES rule chain. For example:
-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
<snip>

This particular rule order causes traffic addressed to an external loadbalancer service on port X to end up on a pod that binds HostPort X on a node. As long as the node with the bound hostport is in the load balancer's target pool, all packets destined for the service will end up on an entirely different pod.

For comparison, here's the rule chain generated by KubeNet:
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m comment --comment "kube hostport portals" -m addrtype --dst-type LOCAL -j KUBE-HOSTPORTS

This difference is caused by CNI using an Insert(0) rule via PrependUnique here:
https://github.com/containernetworking/plugins/blob/master/plugins/meta/portmap/chain.go#L109

For comparison, kubenet uses an Append here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/hostport/hostport.go#L133

The reason that the --dst-type LOCAL match is not specific enough (at least on GCE) is explained in a comment by Tim Hockin here (TLDR is that GCE generates a local route for any load balancer VIPs fronting a GCE VM):
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/userspace/proxier.go#L862

**Comment by squeed** [comment]
Trying to master the iptables ordering game is quite difficult  - for example, on hosts that run firewalld, we need to make sure we run *before* firewalld. So while switching the order would fix your problem, it would create them for others.

The solution Tim and I came up with back in the day when discussing the initial design was to provide the configuration flags `conditionsV4` `conditionsV6`. These are appended to the `-j HOSTPORT-DNAT` rule. Can you express an excluding predicate in this way?

**Comment by varunmar** [comment]
I agree that the iptables ordering game is difficult and error prone and making the CNI-HOSTPORT-DNAT reject the LB traffic sounds much more robust.
Thanks for the pointer to conditionsV4/6, I'll take a look at those and see if adding a reject for traffic from outside the cluster is enough.

**Comment by squeed** [comment]
And if you figure it out, feel free to suggest improvements to the README!

**Comment by liucimin** [comment]
/cc @squeed
The solution Tim and I came up with back in the day when discussing the initial design was to provide the configuration flags conditionsV4 conditionsV6. These are appended to the -j HOSTPORT-DNAT rule. Can you express an excluding predicate in this way?

Sorry to brother u.
Would u tell me how to use  appended the configuration flags conditionsV4 conditionsV6  to the -j HOSTPORT-DNAT rule?
Or what command i can show this flags?

**Comment by bboreham** [comment]
Is this fixed by https://github.com/containernetworking/plugins/pull/269 ?
