### ISSUE TITLE
Inconsistent Result documentation

### ISSUE THREAD

**Issue by andybradshaw** [containernetworking/cni#581]
It looks like there are some inconsistencies in the `String()` function between the `Result` interface and struct. The interface is [documented](https://github.com/containernetworking/cni/blob/5ef0e9aa4cdb7c8d9647d81c93ae0c7139f19f71/pkg/types/types.go#L100) as returning the JSON representation of the result,  while the struct is [documented](https://github.com/containernetworking/cni/blob/47cf2da00befcca6fdd5d58ae044e399945c4b09/pkg/types/current/types.go#L213) as returning some formatted string that isn't JSON.

Not sure which direction should be fixed here, but the documentation should at least be consistent.

**Comment by amshinde** [comment]
I recently ran into this, looks like the String() function returns a formatted string, not JSON.

**Comment by jellonek** [comment]
Also docstring says about form enclosed in `[]` while constructed string does not have that. I'll try to find time today to make PR against that.

**Comment by rosenhouse** [comment]
Can we just delete this method? How are people using this method today?

(copying this comment in from the PR)

**Comment by bboreham** [comment]
There is prior art in Go for a method called `String()` - it is in the `fmt.Stringer` interface and it typically returns a human-readable string.

Hence I think there should be no `String()` method in `Result`, and the implementation is ok as-is.

If people need a JSON-returning method it should be named something like `JSON()`

To underling @rosenhouse comment, we'd like to know how people are using or expect to use this method.

**Comment by dcbw** [comment]
> If it should be leaved in simplified version instead of JSON - imo it should be at least supplemented with info about `Routes`.

@jellonek agreed, let's just do that.
