### ISSUE TITLE
Pods Ips diferent from PodCIDR

### ISSUE THREAD

**Issue by brunovlucena** [containernetworking/cni#585]
Hi all, 

The bridge plugin seems not be setting up the bridge-interface's ip correctly. Any suggestions? I am using kube-router.
 
![screenshot from 2018-09-14 15-24-50](https://user-images.githubusercontent.com/20466126/45552935-bcc98880-b832-11e8-8f8f-b14d0c0fc86f.png)

I started a long thread with more prints in https://github.com/cloudnativelabs/kube-router/issues/537 which may help to explain where i am

Thank you all.

**Comment by squeed** [comment]
I suspect you're reading the wrong CNI configuration file - make sure your bind mounts are correct and you know which directory kubelet is using. 

I just tested you configuration with `cnitool` and it worked correctly:

```
$ sudo ip netns add testing
$ sudo CNI_PATH=./bin ../cni/bin/cnitool add kubernetes /var/run/netns/testing
$ ip -br addr list dev kube-bridge
kube-bridge      UP             10.100.0.1/24 fe80::d06c:ccff:fe84:941b/64 
```

**Comment by brunovlucena** [comment]
You are right! I am using k8s 1.11.

--cni-conf-dir string
  | The full path of the directory in which to search for CNI config files. Default: /etc/cni/net.d

if i don't pass the parameter it does not read the path. Is it a bug?

**Comment by brunovlucena** [comment]
I was too fast... it is not the problem. I deleted the cluster and created again so the problem still persists... it was just a coincidence that matched. the assigments seem to be at random

**Comment by brunovlucena** [comment]
If i setup manualy networking as i supose it should be i receive an error from k8s

![screenshot from 2018-09-14 16-39-33](https://user-images.githubusercontent.com/20466126/45557044-061ed580-b83d-11e8-9ea2-f07b85a8c447.png)

![screenshot from 2018-09-14 16-40-31](https://user-images.githubusercontent.com/20466126/45557052-0a4af300-b83d-11e8-8058-e0ace0acfff3.png)

**Comment by squeed** [comment]
That means you brought up the bridge with the wrong config, then changed the ip address. You probably need to reboot.
