### ISSUE TITLE
No routing entry for CrashLoopBackOff pod (kubernetes)

### ISSUE THREAD

**Issue by gerardo8a** [containernetworking/cni#589]
I'm using CNI version 0.7.1 , but I've seen this happened in earlier versions too. Basically the pod goes into a crash state, the reason is because the route is removed at some point but the ip allocation for the pod is not. Meaning that when the pod tries to recover the route will not be added again, this seems to be because the ip is already allocated to the pod so no need to go to all the process of assigning ip and adding the route. 

The pod will stay in this state until we delete it. Deletion will remove everything, ip and route. I don't have a a way to reproduce, but once I add the route for the missing pod the pod recovers.

Its been tricky to find the root cause because it seems kubelet calls ptp , but there is no logging output from ptp, so if an error occurred in ptp I'm not able to get it anywhere. If you know a way I can get a more verbose logging besides adding verbose level to kubelet (I already did) please let me know. 

Thanks

**Comment by gerardo8a** [comment]
A little more information about my debugging. Add a little bit more logging to ptp and when docker sandbox crashes kubelet tries to bring the pod back again, this is when ptp gets executed again. But for some some reason the route to that particular pod got deleted (not sure who or what deletes the route) so when kubelet tries to bring the pod back it calls again ptp but because the pod IP is already assigned then the route does not get added again.

This is the error I get.
```nl_linux.go:444: syscall.Errno(-error): file exists```

We still don't know what removed the route, but isn't a good idea that cni re-tries to re-add in this case?

**Comment by squeed** [comment]
We've seen this in the past; it happens when the CNI binary is pkilled when kubelet is pklled.

The solution is to switch to using CHECK, which will detect containers with broken networking and alert accordingly. CRIO does this, and we would like to get such support in to dockershim.
