### ISSUE TITLE
Long node drain times with portmap CNI plugin

### ISSUE THREAD

**Issue by mcginne** [containernetworking/cni#605]
We have a pretty large scale Kubernetes cluster (v1.10.11) which has 143 nodes, ~6500 services and ~100 pods per node.
It can take up to 1 hour to cleanly drain a node.

During the hour as it is removing pods I see the following itables commands in top regularly:

```
/sbin/iptables -t nat -X CNI-SN-797f3d4f23657c09003fc --wait
/sbin/iptables -t nat -N CNI-SN-797f3d4f23657c09003fc --wait
/sbin/iptables -t nat -S CNI-HOSTPORT-SNAT --wait
/sbin/iptables -t nat -S CNI-HOSTPORT-DNAT --wait
/sbin/iptables -t nat -S OUTPUT --wait
```
(The ID in there changes each time). Each of these takes a few second to run, and then the loop seems to start all over again)

Whilst this is happening I see lots of the following messages repeating in kubelet logs:

```
Dec  6 12:06:34 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: I1206 12:06:34.882478 1943862 cni.go:274] About to del CNI network k8s-pod-network (type=calico)
Dec  6 12:06:42 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: Calico CNI releasing IP address
Dec  6 12:07:04 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: Calico CNI releasing IP address
Dec  6 12:07:50 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: Calico CNI releasing IP address
Dec  6 12:07:50 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: Calico CNI releasing IP address
Dec  6 12:07:50 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: W1206 12:07:50.322217 1943862 cni.go:242] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "05a7559e774fa302f84e794b7d1c3f67c2fdbe51c13295dbe4396900eaf30250"
Dec  6 12:07:50 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: I1206 12:07:50.322442 1943862 cni.go:274] About to del CNI network k8s-pod-network (type=calico)
Dec  6 12:07:50 stage-dal12-carrier5-worker-1001.ibm.com kubelet.service[1943862]: W1206 12:07:50.406771 1943862 cni.go:242] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container "db1b66c439a5cdd8ea6d41f4d20c5e4e2dd4e7cee5e8e52b386a8fbba25fcca3"
```
The node also often goes to `NotReady` status during the drain.

When the drain completed, the iptables activity stopped, and these messages in kubelet.log stopped.

I found that if I remove the following section from `/etc/cni/net.d/10-calico.conf` (we are using calico) then the drain completes in ~5 minutes and I don't see any iptables issues.
```
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
```
OS: Ubuntu 18.04.1 LTS   
Kernel: 4.15.0-32-generic   
Docker: docker://18.6.1

The issues are not just restricted to the drain - if a node evicts pods for any reason, then it can take a long time (over an hour) before the eviction is complete - so is not very good for recovery times.

We have other environments running Ubuntu 16.04 & Kernel 4.4 which suffer even worse as sometimes the iptables calls there can hang for hours.

Is there anything that can be done to improve the performance of this teardown phase of the portmap plugin, as this makes it pretty unusable at this scale?

**Comment by bradbehle** [comment]
This issue also causes our 4.4 kernel workers to not be able to have kube-proxy update iptables with kubernetes services changes, causing rejected connections to kubernetes services that can be very hard to track down.

**Comment by squeed** [comment]
Also, kernel 4.4 is quite old. 4.10 has some significant iptables performance improvements. That may help.
