### ISSUE TITLE
Docuemnt for K8S_POD_NAMESPACE/NAME

### ISSUE THREAD

**Issue by ymmt2005** [containernetworking/cni#606]
To create a CNI plugin that references Kubernetes API objects, there is a
convention that OCI runtimes pass Kubernetes Pod name and namespace
of the infrastructure container via `CNI_ARGS` like this:

    K8S_POD_NAMESPACE=foo;K8S_POD_NAME=bar

However, this convention is not documented anywhere in CNI specification
which makes it hard to create new CNI plugins for Kubernetes pods.

Having notes or links for the convention would be helpful.  Please look into these.

**Comment by dcbw** [comment]
This is not actually a CNI convention, it's a Kubernetes convention. CNI is a runtime-agnostic project and does not formalize conventions that are specific to container runtimes. So this should be formalized in Kubernetes documentation instead.

**Comment by ymmt2005** [comment]
@dcbw 
Do you know who/where should I tell this for Kubernetes?
Thanks in advance!

**Comment by jellonek** [comment]
That would be someone from https://github.com/kubernetes/community/tree/master/sig-network so ... @dcbw would be also a good candidate ;)
