### ISSUE TITLE
CNI_IFNAME not working in cnitool 0.6.0, is working in 0.5.2

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/cni#630]
CNI_PATH="/usr/libexec/cni/" NETCONFPATH="/etc/mesos-cni" CNI_IFNAME="eth1" cnitool-0.5.2 add test-ptp /var/run/netns/testing

creates as expected an interface eth1

**Comment by dcbw** [comment]
@mccv1r0 can you take a look at this?

**Comment by mccv1r0** [comment]
Isn't this fixed via [PR 587](https://github.com/containernetworking/cni/pull/587)

**Comment by bboreham** [comment]
Closing as duplicate of #586.

We should really do a release.
