### ISSUE TITLE
 docker_sandbox.go:353] failed to read pod IP from plugin/docker: NetworkPlugin cni failed on the status hook for pod "nm-7_ns5": CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container

### ISSUE THREAD

**Issue by xiaoqge** [containernetworking/cni#644]
I have encountered a problem with cni, I am using macvlan, I wrote ipam to manage the IP address of macvlan, the use has been normal, but today there is a very strange exception。

The IP address obtained using the command `kubectl get pods nm-7 -o wide` is 172.17.4.89
![2](https://user-images.githubusercontent.com/8544686/55046009-f8170080-507a-11e9-9e59-e2bb0634fb07.jpeg)

But entering the container found that the ip address is 172.17.3.57
![2](https://user-images.githubusercontent.com/8544686/54984167-3cf25700-4fe9-11e9-971c-33f2b61ca881.png)

I found an error log in the system log that coincides with the log of ipam allocation ip address time, so what is the impact of this error?

![WechatIMG6](https://user-images.githubusercontent.com/8544686/55045940-b7b78280-507a-11e9-8ec6-f58efd92aab8.png)

**Comment by bboreham** [comment]
Your question appears to relate to Kubernetes rather than CNI.
"cannot find namespace for terminated container" is expected, if kubelet is cleaning up after some previous failure.
