### ISSUE TITLE
What causes two cmdAdd or cmdDel calls in a row

### ISSUE THREAD

**Issue by xichengliudui** [containernetworking/cni#656]
**I have raised this issue at k8s, but I think it may be caused by cni**.

*What causes two cmdAdd or cmdDel calls in a row?*

* the K8S event shows that this pod was created/started twice, and the fabric log sees two cmdAdd/cmdDel calls

log information: https://github.com/xichengliudui/public-repo/blob/master/logs-03.md#view-the-pod-event

**Comment by xichengliudui** [comment]
I don't think cni will call add or del twice in a row.

**Comment by bboreham** [comment]
It looks like your question is about Kubernetes.  See https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/ for ideas on how to get help.

CNI is a cross-platform standard; it makes some statements [in the spec](https://github.com/containernetworking/cni/blob/master/SPEC.md#general-considerations) about sequencing of operations, but cannot enforce whether a particular runtime follows them.
