### ISSUE TITLE
Slack app is dead

### ISSUE THREAD

**Issue by benmoss** [containernetworking/cni#657]
https://cryptic-tundra-43194.herokuapp.com/ is 404ing now

**Comment by bboreham** [comment]
Hopefully someone knows how to resurrect that, but in the meantime I'll offer to invite you by hand if you email bryan at weave dot works.

**Comment by xichengliudui** [comment]
@bboreham ，can this problem be fixed? If it can't be fixed, do we need to update a new slack

**Comment by bboreham** [comment]
I don’t know anything about the thing that is broken. Probably someone who knows about it can fix it. 

Other Slack inviters are available.

**Comment by benmoss** [comment]
The CNI slack is pretty dead itself, maybe it could be rolled into the Kubernetes slack?
