### ISSUE TITLE
support config caching for changing network freely

### ISSUE THREAD

**Issue by mars1024** [containernetworking/cni#660]
As we know, CRI usually does not support multi CNI networks, in order to avoid the cni network config inconformity between ADD and DEL, we have to set a default name to avoid different cni network reloading real-time by file sorting like [ocicni](https://github.com/cri-o/ocicni/blob/a4c8e18142f8848e94a3bc2894e2a7e9ced3d1c3/pkg/ocicni/ocicni.go#L27). 

But this will make CRI use CNI inflexibly, for example, if we put a new cni network config in `/etc/cni/net.d`, even it comes first in file sorting, it can not be the default network as we expected until we restart CRI or CNI manager.

So I think if we want to use different networks freely (like switching among flannel, calico or something else) in scene of CRI, we have to cache cni network config and runtime config on disk when ADD, and make DEL or CHECK use these configs firstly. Based on this, DEL will never fail no matter how default network change.

**Comment by mars1024** [comment]
ref [https://github.com/cri-o/ocicni/pull/31](https://github.com/cri-o/ocicni/pull/31)  @dcbw

**Comment by bboreham** [comment]
I don't understand what you are saying.  Here are some clarifying remarks:
 - CNI allows multiple networks.
 - CNI doesn't look in `/etc/cni/net.d`, or read config files - config comes via stdin.
 - CNI doesn't impact on CRI, except via the CNI spec.
 - Anyone calling DEL is required to supply the correct config, matching a preceding ADD.

Sounds like you might have requirements from CRI implementations, but what exactly do you need from CNI?

**Comment by mars1024** [comment]
> I don't understand what you are saying. Here are some clarifying remarks:
> 
> * CNI allows multiple networks.
> * CNI doesn't look in `/etc/cni/net.d`, or read config files - config comes via stdin.
> * CNI doesn't impact on CRI, except via the CNI spec.
> * Anyone calling DEL is required to supply the correct config, matching a preceding ADD.
> 
> Sounds like you might have requirements from CRI implementations, but what exactly do you need from CNI?

CRI usually need a CNI manager(like cniNetworkPlugin in kubernetes or ocicni) to load CNI configs and use them to help setting up pods' network, I think a CNI manager should have the ability to load CNI configs real-time, but this maybe confused because if CNI config changes in CNI manager, the old pods which is set up by old CNI config will not be tore down successfully because a new CNI config has been loaded and CRI has no idea about this.
So I think we need a config caching on disk in CNI ADD, and when DEL or CHECK happens, we will use the caching config firstly, even a new CNI config is used now, we can tear down old pods successfully.

I have a discussion with @dcbw about this on [https://github.com/cri-o/ocicni/pull/31](https://github.com/cri-o/ocicni/pull/31), you can see some details there.

Moreover, I think this PR #661 is resolving this issue.

**Comment by squeed** [comment]
We have talked about this pretty extensively in previous maintainer's meetings, and the decision is almost certainly that we don't want to do it.

Consider the counterexample: you use the infoblox ipam plugin, which takes a reference to an external server. If you want to change that server's URL, then that change should take effect immediately, including for deletion of existing containers.

(BTW, #661 does not resolve this, it just makes some details around DEL easier for the runtime)

It is the runtime's responsibility to select the correct CNI configuration file. The way that Kubernetes does it is unfortunate, and we have an opportunity to change that, but the problem is at that level, not here.

**Comment by mars1024** [comment]
@squeed @bboreham @dcbw  Thanks all for your attentions and discussions, I think I've got your point that libcni have no ability to decide which is the correct configuration even it has some config caching. 
And I think we can do the caching job in cni manager like ocicni and cniNetworkPlugin in k/k, I'll have a further discussion with @dcbw on this there.
When the discussion ends, I will put the result here and close this. Thanks again !

**Comment by dcbw** [comment]
Config caching was added to CNI and also to upstream CRIO/kubelet.
