### ISSUE TITLE
delegate : allow delegation funcs override CNI_COMMAND env automatically

### ISSUE THREAD

**Issue by mars1024** [containernetworking/cni#665]
Delegation funcs(DelegateAdd, DelegateDel ...) now will inherit all CNI-related envs (CNI_COMMAND, CNI_IFNAME ...) from main process, and they have a [pre-check](https://github.com/containernetworking/cni/blob/f726df9103d27044c93c99e30f6fb04048606444/pkg/invoke/delegate.go#L31) of CNI_COMMAND. 

Sometimes, we need a DEL exec for another CNI plugin in a main CNI plugin process, such as a ipam revert in ADD exec of macvlan plugin (ref to discussions in [https://github.com/containernetworking/plugins/pull/301](https://github.com/containernetworking/plugins/pull/301)), in this scenario, we have to set CNI_COMMAND to DEL and revert it after delegation. 

So I think delegation func should have the ability to override CNI_COMMAND env in process environments heritance automatically. This will help us to avoid setting and unsetting CNI_COMMAND env again and again, what's more, to avoid some additional risk.

**Comment by mars1024** [comment]
pr ref #663

**Comment by dcbw** [comment]
#663 merged.
