### ISSUE TITLE
Deployment binaries for v0.7.0

### ISSUE THREAD

**Issue by rafaelmagu** [containernetworking/cni#667]
I noticed v0.7.0 has been deployed 16 days ago but no binary packages have been added to the release. Is this an expected change? Will future releases also forgo pre-built binaries?

**Comment by bboreham** [comment]
The plugins moved to another repo https://github.com/containernetworking/plugins

This repo contains the spec and library, for which no binaries are needed.

**Comment by rafaelmagu** [comment]
Oh, thanks for the update!

**Comment by Bregor** [comment]
@bboreham you mean `cnitool` binary is not needed anymore?
There is no `cnitool` and `noop` in plugins archive.

**Comment by bboreham** [comment]
Those are tools used by developers - if you explain why you need them released rather than build your own we can consider it.

**Comment by Bregor** [comment]
Ah, got it.
Thank you.
