### ISSUE TITLE
help track down malformed CNI plugin result

### ISSUE THREAD

**Issue by dbyron0** [containernetworking/cni#670]
I'm trying to track down a problem in a CNI plugin and feel like some extra logging here would really help.  The log messages I'm staring at are:
```
May 20 11:06:45 ip-10-110-138-29 kubelet[1778]: E0520 11:06:45.220220    1778 cni.go:259] Error adding network: unexpected end of JSON input
May 20 11:06:45 ip-10-110-138-29 kubelet[1778]: E0520 11:06:45.220260    1778 cni.go:227] Error while adding to cni network: unexpected end of JSON input
```
I'd sure love to know what the actual bytes are that are causing the error.  If I'm reading the code correctly, those bytes come from stdOut.Bytes() [here](https://github.com/containernetworking/cni/blob/master/pkg/invoke/raw_exec.go#L43)
and then [this code](https://github.com/containernetworking/cni/blob/master/pkg/types/current/types.go#L34) is what fails to decode it.

I'm running kubernetes 1.10.7, but I believe I'd see the same thing from the head of master which is why I've linked to that code.

I don't see any other log messages here, so I'm not sure what makes sense.

Thanks for your help.

**Comment by bboreham** [comment]
It depends on how your kubelet is set up, first of all the "network plugin".
If "kubenet" it's generated; if "cni" it's from a file (default location `/etc/cni/net.d/`)

**Comment by dbyron0** [comment]
Pretty sure it's cni.
```
# cd /
root@ip-10-110-138-29:/# ls -la /etc/cni/net.d
total 12
drw-r--r-- 2 root root 4096 Feb  4 05:13 .
drwxr-xr-x 3 root root 4096 Feb  4 05:13 ..
-rw-r--r-- 1 root root  555 Feb  4 05:13 10-cni-ipvlan-vpc-k8s.conflist
```
```
# cat /etc/cni/net.d/10-cni-ipvlan-vpc-k8s.conflist 
{
    "cniVersion": "0.3.1",
    "name": "cni-ipvlan-vpc-k8s",
    "plugins": [
	{
	    "cniVersion": "0.3.1",
	    "type": "cni-ipvlan-vpc-k8s-ipam",
	    "interfaceIndex": 1,
		"skipDeallocation" : true,
	    "subnetTags":  {"Type":"pods"},
	    "secGroupIds": ["sg-XXXXXXXX"]
	},
	{
	    "cniVersion": "0.3.1",
	    "type": "cni-ipvlan-vpc-k8s-ipvlan",
	    "mode": "l2"
	},
	{
	    "cniVersion": "0.3.1",
	    "type": "cni-ipvlan-vpc-k8s-unnumbered-ptp",
	    "hostInterface": "eth0",
	    "containerInterface": "veth0",
	    "ipMasq": true
	}
    ]
```

**Comment by bboreham** [comment]
That file needs, at least, a closing brace. 

(I’m conscious now that you said it was the result that is giving an error, and this is the input, but it does seem malformed so let’s go with it)

**Comment by dbyron0** [comment]
That was a copy-paste error on my part.  The closing brace is really there:
```
# cat /etc/cni/net.d/10-cni-ipvlan-vpc-k8s.conflist 
{
    "cniVersion": "0.3.1",
    "name": "cni-ipvlan-vpc-k8s",
    "plugins": [
	{
	    "cniVersion": "0.3.1",
	    "type": "cni-ipvlan-vpc-k8s-ipam",
	    "interfaceIndex": 1,
		"skipDeallocation" : true,
	    "subnetTags":  {"Type":"pods"},
	    "secGroupIds": ["sg-XXXXXXXX"]
	},
	{
	    "cniVersion": "0.3.1",
	    "type": "cni-ipvlan-vpc-k8s-ipvlan",
	    "mode": "l2"
	},
	{
	    "cniVersion": "0.3.1",
	    "type": "cni-ipvlan-vpc-k8s-unnumbered-ptp",
	    "hostInterface": "eth0",
	    "containerInterface": "veth0",
	    "ipMasq": true
	}
    ]
}
```

**Comment by squeed** [comment]
The easiest way to track these things down is to manually execute the configuration via cnitool. I'd do something like

```
ip netns add testing
cnitool add cni-ipvlan-vpc-k8s /var/run/netns/testing
```

From the looks of your CNI configuration, it seems strange that the ipam isn't part of the ipvlan's configuration.

**Comment by squeed** [comment]
Closing for now; if you find an issue, please re-open.
