### ISSUE TITLE
how to get on this cni-dev google mailing list.

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/cni#673]
It is just to ridiculous to ask. But how to get on this stupid google mailing list. It is in !@#$!@ polish, and cannot change the language. Why not use a normal mailing list system like these http://lists.ceph.com/listinfo.cgi/ceph-users-ceph.com

![20190530-160603-groups google com](https://user-images.githubusercontent.com/13450219/58638439-1efce780-82f5-11e9-9045-b2d7a22da3fa.png)

**Comment by bboreham** [comment]
If you drop down the button with a person and a cog-wheel, the third option should be "Change display language".
