### ISSUE TITLE
where can I find the complete syntax/options/layout of  { "args": { "cni":

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/cni#676]
I am reading/writing in a plugin to args->cni->ips. And would like to preserve any other keys that have been submitted.  For that I would like to know what all can be in this section of the json. Where is this documented?

```
{
  "args": {
    "cni": {
      "ips": [ "192.168.122.171" ]
    }
```

**Comment by bboreham** [comment]
There is no complete list; `args` is intended to be used by runtimes and plugins as they desire.
We have documented some conventions at https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#args-in-network-config

The spec says this field can be used for anything at https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration
