### ISSUE TITLE
some help with the args cni json please

### ISSUE THREAD

**Issue by f1-outsourcing** [containernetworking/cni#677]
I am reading and writing in a plugin to args->cni->ips. And when I do I have noticed that the ipss section is removed. I think this is because I have chosen incorrect types. I got this from some source code, but I guess this is not complete. 

Anyone an idea how I should the cni struct? Maybe with an example?

```
type CniArgs struct {
        Args struct {
                Cni IPAMArgs `json:"cni"`
        } `json:"args"`
}

type IPAMArgs struct {
        Ips []net.IP `json:"ips"`
}
```

ipss from below is (of course) deleted from the json, but so will other maybe valid keys.
```
{
  "args": {
    "bla": {
      "rs": [
        "192.168.10.10"
      ]
    },
    "cni": {
      "ipss": [ "192.168.122.172" ],
      "ips": [ "192.168.122.171" ]
    }
```

**Comment by bboreham** [comment]
Sorry this didn't get a response for a long time.  
I don't understand your question.  Where does `ipss` come from?

**Comment by f1-outsourcing** [comment]
I just added it as an example. I would like to know what I all can put there for instance the interface. So the CNI_INTF/CNI_INF? environment is set

**Comment by bboreham** [comment]
Are you asking how to preserve sections of the JSON that are not explicitly matched in your struct?

**Comment by bboreham** [comment]
Please reopen if you come back to this - and say more about what you are trying to do.
