### ISSUE TITLE
Execute test case with no root user on ubuntu

### ISSUE THREAD

**Issue by smarkm** [containernetworking/cni#680]
When I execute the test of a bridge with no root user on ubuntu got an error about mount,
```
  Expected error:
      <*errors.errorString | 0xc420076f90>: {
          s: "mount --make-rshared /var/run/netns failed: \"operation not permitted\"",
      }
      mount --make-rshared /var/run/netns failed: "operation not permitted"
  not to have occurred
```

It seems the `mount --make-rshared` should be use root, any solution about this problem or I should be use root for testing?

**Comment by bboreham** [comment]
I wouldn't give "use root" as a blanket instruction, but configuring the network needs certain privileges, e.g. `CAP_NET_ADMIN`; for simplicity we generally show examples run as root via `sudo`.

If you arrived in your situation by following instructions in this repo please say where.

**Comment by smarkm** [comment]
I'm just testing in `vscode` and it's not with `sudo`, it's a common certain privileges problem not relate about this code, it's working well under the shell, Thank you @bboreham
