### ISSUE TITLE
CNI on Anaconda

### ISSUE THREAD

**Issue by adbeda** [containernetworking/cni#696]
CNI and the Plugins are available to the Anaconda users community through the conda-forge channel. 

#### Installation
CNI
        
         conda install -c conda-forge cni

CNI-Plugins

        conda install -c conda-forge cni-plugins

Best!

**Comment by bboreham** [comment]
Hi @adbeda, would you like to make a PR to add a line pointing to your instructions in https://github.com/containernetworking/cni/blob/master/README.md ?

(I guess it could go under Container Runtimes?)
