### ISSUE TITLE
plugins: test if ipvlan and macvlan can work at the same time

### ISSUE THREAD

**Issue by steveeJ** [containernetworking/cni#7]
I could not simultaneously use both on the same ethernet NIC when testing manually using the `ip` util. This needs to be investigated further using the plugins, since applications like rkt will eventually want to use both at the same time.

**Comment by eyakubovich** [comment]
I would not be surprised if two different types of devices cannot enslave the same interface. Obviously it's not ideal but it'll just have to be a restriction.

**Comment by jonboulle** [comment]
What do we need here then? Will the ipvlan/macvlan plugins just error out if this occurs?

**Comment by eyakubovich** [comment]
Yes, they should just error out during enslaving process but this needs to be double checked and documented.

**Comment by steveeJ** [comment]
I checked the behaviour in different contexts when trying to utilize macvlan and ipvlan at the same time

##### iproute2
Out of interest I also checked macvtap, which will be interesting for the qemu networking. It's also blocked by ipvlan.

```
phyhost2 ~ # ip link add link em1 type ipvlan
phyhost2 ~ # ip link add link em1 type macvlan
RTNETLINK answers: Device or resource busy
phyhost2 ~ # ip link add link em1 type macvtap
RTNETLINK answers: Device or resource busy
```

##### priv-net-run.sh script
```
$ sudo CNI_PATH=$CNI_PATH ./priv-net-run.sh ip l
ipv6-public-2 : error executing ADD
```

##### rkt
```
2015/05/22 00:20:19 Setup: executing net-plugin ipvlan
2015/05/22 00:20:19 Setup: executing net-plugin macvlan
2015/05/22 00:20:19 Teardown: executing net-plugin ipvlan
Failed to setup network: error adding network "ipv6-public-2": exit status 1
```

As @eyakubovich expected the plugins return an error to the application which obviously needs to be handled more gracefully than seen above.

**Comment by steveeJ** [comment]
It would be good to give according error messages in this case. What's the best approach here @eyakubovich? Is it worth evaluating the state on the filesystem?

**Comment by steveeJ** [comment]
I just wanted to add notes to the documentation of ipvlan and macvlan, and noticed that both docs already mention that these are not compatible on the same master interface. Best work is done work!

**Comment by dcbw** [comment]
@steveeJ I don't think that's quite true; what's not supported is creating an ipvlan off a macvlan interface and vice-versa.  You can certainly create separate macvlan and ipvlan children off the same ethernet master, at least that's my understanding.

**Comment by steveeJ** [comment]
@dcbw 

> I don't think that's quite true; what's not supported is creating an ipvlan off a macvlan interface and vice-versa. You can certainly create separate macvlan and ipvlan children off the same ethernet master, at least that's my understanding.

I just verified this again, in case something changed in the kernel since my original findings.

```
root@steveej-laptop ✓ /home/steveej
# ip link add link enp0s20u3u1u3 type ipvlan
root@steveej-laptop ✓ /home/steveej
# ip link add link enp0s20u3u1u3 type macvlan
RTNETLINK answers: Device or resource busy
root@steveej-laptop ✗ /home/steveej
# uname -r
4.6.0
```

**Comment by dcbw** [comment]
Looking at the kernel code again, you are correct and I am wrong.

**Comment by dcbw** [comment]
```
static int macvlan_port_create(struct net_device *dev)
{
	struct macvlan_port *port;
	unsigned int i;
	int err;

	if (dev->type != ARPHRD_ETHER || dev->flags & IFF_LOOPBACK)
		return -EINVAL;

	if (netif_is_ipvlan_port(dev))
		return -EBUSY;
```
