### ISSUE TITLE
cniConf.DelNetworkList fails with `failed to convert cached result version`

### ISSUE THREAD

**Issue by fiws** [containernetworking/cni#701]
I'm trying to use cni with containerd but can't get `cniConf.DelNetworkList` working. It always ends up with the same error.

I assume that i need to call that after the container ran. Otherwise I get `failed to allocate for range 0: 10.55.0.x has been allocated to some-container-name, duplicate allocation is not allowed`

It could be that my config is wrong, or I am not using cni correctly (I don't know – there is not a lot of documentation on this)

Happy for any help!

```golang
bridgeConf, _ := libcni.ConfListFromFile("./bridge-conf.json")
rc := libcni.RuntimeConf{
	ContainerID: task.ID(),
	NetNS:       fmt.Sprintf("/proc/%d/ns/net", task.Pid()),
	IfName:      "eth0",
}

// add container to network
_, err := cniConf.AddNetworkList(ctx, bridgeConf, &rc)
if err != nil {
	return err
}

exitStatusC, err := task.Wait(ctx)
if err != nil {
	return err
}

// start the container
if err := task.Start(ctx); err != nil {
	return err
}

// wait for the process to fully exit
status := <-exitStatusC
code, _, err := status.Result()

// THIS FAILS ↓
if err := cniConf.DelNetworkList(ctx, bridgeConf, &rc); err != nil {
	return err
}
```

## Result

```
panic: failed to get network "craft0" cached result: failed to convert cached result version "0.1.0" to config version "0.4.0": cannot convert version ["" "0.1.0" "0.2.0"] to 0.4.0
```

## Config

```
{
  "cniVersion": "0.4.0",
  "name": "net0",
  "plugins": [
    {
      "cniVersion": "0.4.0",
      "type": "bridge",
      "bridge": "test0",
      "isDefaultGateway": true,
      "forceAddress": false,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "subnet": "10.55.0.0/16"
      },
      "dns": {
        "nameservers": [ "8.8.8.8" ]
      }
    },
    {
      "cniVersion": "0.4.0",
      "type": "firewall"
    },
    { 
      "cniVersion": "0.4.0",
      "name": "lo",
      "type": "loopback" 
    }
  ]
}
```

## Environment

OS: Arch Linux
plugins version: [0.8.2](https://www.archlinux.org/packages/community/x86_64/cni-plugins/)

**Comment by fiws** [comment]
I figured out that cni tries to read `/var/lib/cni/results/networkname-containerid-ifname`. That file looks like this: `{"dns":{}}` – this obviously is the problem, but why is like this?

**Comment by mccv1r0** [comment]
Are you sure the CNI ADD worked?

Your config has both ```"type": "bridge"``` and ```"type": loopback``` plugins in it.  There should be just one CNI main plugin per config, bridge or loopback  supplied to ADD (then later to DEL etc.)

Each ADD will create one Linux network device (i.e. either ```lo``` or ```test0```  using your config) which will show up if you used ```ip addr show``` inside the container.  The name is also the ```ifname``` at the end of the file ```/var/lib/cni/results/networkname-containerid-ifname```

**Comment by fiws** [comment]
Thanks for clearing things up!

My invalid (?) config did indeed work. See container output below:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether c2:fc:26:f6:4a:62 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.55.0.10/16 brd 10.55.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::c0fc:26ff:fef6:4a62/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

I removed the `"type": "loopback` block and everything started working again, thanks.

I have one follow up question: `cniConf.DelNetworkList` now fails with `failed to Statfs "/proc/17941/ns/net": no such file or directory` – I guess this is because the process already is gone. Do I need to create my own network namespace or is there a way around this?

**Comment by dcbw** [comment]
@fiws this is actually a bug in the loopback plugin, it should pass the prevResult through rather than just an empty result (which overwrites the one from bridge). Or, you could put the loopback plugin *first* in the chain (before bridge) and that will also work.

Thanks for the report, I filed https://github.com/containernetworking/plugins/issues/376 to track the loopback issue.
