### ISSUE TITLE
cni repo, README.md hyperlink cannot find the page

### ISSUE THREAD

**Issue by xichengliudui** [containernetworking/cni#717]
![image](https://user-images.githubusercontent.com/40875627/65825098-46fd5700-e2a5-11e9-9a39-6888bbf55036.png)
**Click on the hyperlink**
![image](https://user-images.githubusercontent.com/40875627/65825110-7b711300-e2a5-11e9-9eda-a7f7d3e98dca.png)

**Comment by xichengliudui** [comment]
Can we create an images directory for these images? Just like logo.png, it's in the root directory

**Comment by bboreham** [comment]
The underlying problem is #657
