### ISSUE TITLE
missing CNI version in config fails ValidateNetworkList()/ValidateNetwork()

### ISSUE THREAD

**Issue by dcbw** [containernetworking/cni#720]
A missing cniVersion in config JSON ends up as "". When config validation is called to match the config version with what plugins claim to support, most plugins return:

`var All = PluginSupports("0.1.0", "0.2.0", "0.3.0", "0.3.1", "0.4.0")`

from pkg/version/version.go, like Flannel does:

```
func main() {
	skel.PluginMain(cmdAdd, cmdCheck, cmdDel, version.All, bv.BuildString("flannel"))
}
```

But that fails validation because PluginSupports does not contain "", so validateNetwork() fails:

```
// validatePlugin checks that an individual plugin's configuration is sane
func (c *CNIConfig) validatePlugin(ctx context.Context, pluginName, expectedVersion string) error {
	c.ensureExec()
	pluginPath, err := c.exec.FindInPath(pluginName, c.Path)
	if err != nil {
		return err
	}

	vi, err := invoke.GetVersionInfo(ctx, pluginPath, c.exec)
	if err != nil {
		return err
	}
	for _, vers := range vi.SupportedVersions() {
===>	if vers == expectedVersion {
			return nil
		}
	}
	return fmt.Errorf("plugin %s does not support config version %q", pluginName, expectedVersion)
}
```

**Comment by dcbw** [comment]
Possible solutions are:

- update validatePlugin to manually match expectedVersion=="" against 0.1.0 and 0.2.0
- make ValidateNetwork/ValidateNetworkList marshal the NetConf to bytes, call pkg/version/conf.go Decode(), and use that version rather than directly using list.CNIVersion that may be blank
- update libcni/conf.go to sub "" => "0.1.0" (but this doesn't cover NetConfs that people create themselves)
- make ValidateNetwork/ValidateNetworkList just manually do `if version == "" { version = "0.1.0" }`

**Comment by dcbw** [comment]
@containernetworking/cni-maintainers @mccv1r0

**Comment by squeed** [comment]
@bboreham and I like the first suggestion:

>     * update validatePlugin to manually match expectedVersion=="" against 0.1.0 and 0.2.0
