### ISSUE TITLE
if plugin segfaults/panics, invoke.ExecPlugin... claims it "failed with no error message"

### ISSUE THREAD

**Issue by danwinship** [containernetworking/cni#732]
If a plugin exits with a non-0 exit status and prints stuff to stderr *but not stdout*, then `pkg/invoke/raw_exec.go:pluginErr()` will categorize this as "netplugin failed with no error message". This seems to be in part because it forwards the plugin's stderr to its parent's stderr, which is nice and all, but it means that the stderr might end up getting logged somewhere less useful (eg, in cri-o's logs rather than kubelet's). Plus, the "failed with no error message" part is just wrong.

(Seen in two unrelated contexts with different plugins in the same day, lol)

@dcbw @squeed

**Comment by squeed** [comment]
Yeah, that makes sense. We give plugins the opportunity to output a reasonable error message via json, but that's not always possible.

**Comment by squeed** [comment]
While we're at it, we should interpret the exit code if it indicates abnormal termination.

**Comment by zjj2wry** [comment]
Encountered this problem. kubectl describe pod will only get netplugin failed with no error message

**Comment by bboreham** [comment]
Reopened because I'm not sure how #735 works.

**Comment by dcbw** [comment]
@bboreham can you describe what doesn't sound right to you about #735?

**Comment by dcbw** [comment]
Yeah, I can't see where `c.Run()` in raw_exec.go will create an ExitError that includes stderr output.
