### ISSUE TITLE
Need absolute netns path to write a generic CNI plugin

### ISSUE THREAD

**Issue by L-MA** [containernetworking/cni#74]
Implementation starts to get messy when different orchestrators use different paths to the CNI_NETNS. To configure the netns, we need the absolute path, so for rkt, we do something like this: 

`netns_path = '%s/%s/%s' % (RKT_NETNS_ROOT, env['CNI_CONTAINERID'], env['CNI_NETNS'])`

This will be different for other orchestrators using CNI, so it's currently not clear how to write a generic CNI plugin if the prefix of CNI_NETNS isn't known.

**Comment by jonboulle** [comment]
I don't really follow; why does the plugin need anything other than the absolute path?

**Comment by jonboulle** [comment]
I mean, in rkt we DO pass an absolute`CNI_NETNS` as far as I can tell - where are you seeing the logic you referenced?

**Comment by L-MA** [comment]
I have not dug into the rkt code myself, but the testing I've done with rkt v0.9.0 shows that rkt still passes in the relative `CNI_NETNS` path. I wrote up a simple plugin to show this:
```
luke@test-master:~/rkt-v0.9.0$ cat > 10-test.conf <<EOF
{
    "name": "test",
    "type": "test-rkt"
}
EOF
luke@test-master:~/rkt-v0.9.0$ sudo mv 10-test.conf /etc/rkt/net.d/
luke@test-master:~/rkt-v0.9.0$ cat > test-rkt <<EOF
#!/bin/bash

echo \$CNI_NETNS > ~/netns.txt
EOF
luke@test-master:~/rkt-v0.9.0$ chmod +x test-rkt; sudo mv test-rkt /usr/lib/rkt/plugins/net/
luke@test-master:~/rkt-v0.9.0$ sudo ./rkt run docker://busybox --net=test
luke@test-master:~/rkt-v0.9.0$ cat ~/netns.txt
netns
```

**Comment by eyakubovich** [comment]
We can require absolute path but the plugin can also just `$(PWD)/$CNI_NETNS` to get the full path.

**Comment by Symmetric** [comment]
The latter approach seems to preclude using namespaces of the form `/proc/<pid>/ns/net`, which is what we want to do in our Kubernetes plugin. I think that means that passing an absolute path is more flexible.

**Comment by eyakubovich** [comment]
Why does it preclude the use of relative path? I mean, if the cwd is `/proc/<pid>`, then yes, `ns/net` would be a bad path. If it was `/var/lib/mycontainer`, `../../../proc/<pid>/ns/net` would be fine. Obviously the container runtime has to ensure that the path it provides makes sense when the plugin is executed. But the plugin can just expect any path, relative or absolute, and can make a relative into absolute easily.

I mean all normal Unix commands work fine with both. You can do `ls ./foo/` and `ls /home/me/foo`.

**Comment by caseydavenport** [comment]
I tested this out - it looks like rkt does pass the correct path relative to the `cwd` of the plugin, so I think this is fine.  If anything, I think the `CNI_NETNS` variable should just be documented to include that it can either be an absolute path, or a path relative to the current working directory of the plugin.

Either way, I think this issue can be closed.

**Comment by steveeJ** [comment]
> I mean all normal Unix commands work fine with both. You can do ls ./foo/ and ls /home/me/foo.

This is my general understanding too, and the CNI plugins are no exception.

> Either way, I think this issue can be closed.

Agreed.
