### ISSUE TITLE
Support infiniband GUID in Capabilities / Runtime Configuration

### ISSUE THREAD

**Issue by adrianchiris** [containernetworking/cni#741]
In order to support container network connectivity for infiniband fabric a CNI may require to configure the Infiniband interface GUID before moving the network interface to the pod namespace much like is done today with the [mac Capability/ Runtime config ](https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#well-known-capabilities)for ethernet fabrics.

I would like to propose an addition of the `GUID` capability/ Runtime Configuration which will be consumed initially by [ib-sriov-cni](https://github.com/Mellanox/ib-sriov-cni).

while the `mac` address field may be reused for this purpose it will not be accurate as `mac` address field, as defined by the spec, represents an Interface hardware address.

For IPoIB, an interface's hardware address is composed of 20 octets but only the first (lower) 8 octets are configurable by the user.
According to section 9.1.1 in IPoIB [RFC](https://tools.ietf.org/html/rfc4391):

- bytes 0-3 bytes are flags and queue pair number which user cannot control
- bytes 4-19 GID which is composed as follows (can be found in IBTA Infiniband Specification):
- 8 bytes subnet prefix - set by the infiniband subnet manager (initial value is 0xfe80000000000000)
- 8 bytes GUID - **the element which is user configurable**

As a side note, a CNI handling IPoIB interfaces is expected to return the full 20 octet hardware address in `mac` field under `interfaces` when returning result of an `ADD` command

**Comment by mars1024** [comment]
Actually CNI capabilities/runtime configuration is more like a specification than a specific behavior, if you want to add some kind of capabilities, CNI Manager(like ocicni, cniNetworkPlugin in kubernetes) and CNI plugins should be changed, not CNI itself.

**Comment by adrianchiris** [comment]
Hi, So the goal is to define GUID in the specification (like mac today).
Once we have this well defined in the spec, we will do the needed changes in relevant projects to consume this capabilities/runtimeconfig attribute.

for now we plan to:
1. implement this in [ib-sriov-cni](https://github.com/Mellanox/ib-sriov-cni) CNI plugin
2. implement in multus to pass runtimeConfig to CNI

if needed in the future, support shall be added to CNI manager.

**Comment by jellonek** [comment]
@mars1024 Adrian is only asking for extension in https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#well-known-capabilities - without updating the spec. That's because this doc precisely says that "Additional conventions can be created by creating PRs which modify this document."
So it's probably (IMO) only about adding an additional entry after https://github.com/containernetworking/cni/blob/722a48807037ce5f2caa95a3e70b403bbd915b90/CONVENTIONS.md#L65

**Comment by jellonek** [comment]
@adrianchiris it's not in specification, but in an additional document about "conventions".

**Comment by jellonek** [comment]
@mars1024 btw. take a look on https://github.com/k8snetworkplumbingwg/multi-net-spec/issues/4#issuecomment-575446224

**Comment by mars1024** [comment]
> Hi, So the goal is to define GUID in the convention document (like mac today).
> Once we have this well defined in the spec, we will do the needed changes in relevant projects to consume this capabilities/runtimeconfig attribute.
> 
> for now we plan to:
> 
> 1. implement this in [ib-sriov-cni](https://github.com/Mellanox/ib-sriov-cni) CNI plugin
> 2. implement in multus to pass runtimeConfig to CNI
> 
> if needed in the future, support shall be added to CNI managers.

Got it! A PR about convention is definitely welcomed.

**Comment by dcbw** [comment]
PR #742  has merged
