### ISSUE TITLE
why v0.7.1 only have 2 assets ??

### ISSUE THREAD

**Issue by 4ss3g4f** [containernetworking/cni#748]
why v0.7.1 only have 2 assets ??

currently we can only used https://github.com/containernetworking/cni/releases/download/v0.6.0/cni-amd64-v0.6.0.tgz ,

because there is no available v0.7.1 to download

**Comment by bboreham** [comment]
Is your question answered at #667?

**Comment by 4ss3g4f** [comment]
Yes it did, we need to build the binary our self with the provided script,

Thank you

**Comment by bboreham** [comment]
Good to hear.  I made a note on the releases page; hope this will help the next person.
