### ISSUE TITLE
Standardize consumption of a network resource by CNI  (deviceID / pciBusID)

### ISSUE THREAD

**Issue by adrianchiris** [containernetworking/cni#757]
Today there are CNI's that require a resource in order to setup network for a container.

- sriov CNI relies on "deviceID" attribute to be passed as part of the network configuration in order to setup network for the allocated VF.
- host-device CNI relies on "pciBusID" attribute to be passed as part of the network configuration in order to setup network.

to my knowledge these CNI's are invoked by a delegate plugin which injects these attributes to the CNI's network configuration before invoking the CNI.

As other CNI's might require the resource associated with the network (working on one as we speak... :) )  i think its worth standardizing it as part of runtime capabilities/config as this attribute is injected by the runtime.

**Comment by adrianchiris** [comment]
@s1061123

**Comment by dcbw** [comment]
@adrianchiris I believe the host-device pciBusID is just the config struct value; we can standardize a runtimeConfig value for `deviceID` and host-device can simply consume it, if passed, if its conf value `pciBusID` is not present.

**Comment by dcbw** [comment]
@adrianchiris would you like to create a PR to add a deviceID to CONVENTIONS.md?

**Comment by adrianchiris** [comment]
@dcbw sure.

**Comment by bboreham** [comment]
Closed by #761
