### ISSUE TITLE
Cleanups for 1.0

### ISSUE THREAD

**Issue by squeed** [containernetworking/cni#771]
We were talking about things we'd like to **remove** before we cut 1.0, since anything in the spec can never be removed.

- [ ] ~Result ips.gateway is redundant and should be removed~
- [x] Result ips.version is redundant
- [ ] ~Result routes.gw should be an array~
- [x] Useful, structural examples in spec (e.g. how the "args" work)
- [x] remove non-ConfigList configuration
- [ ] ~remove CNI_ARGS~

**Comment by bboreham** [comment]
We decided to strike the first item after hearing that some plugin authors find it useful to supply a gateway.

**Comment by bboreham** [comment]
We should also put more detail into the spec highlighting the differences between the data type read in by CNI and the data type output to the plugin.
