### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by aojea** [containernetworking/cni#773]
There are an interesting number of projects that are vendoring the CNI library 

https://github.com/search?l=Go&q=github.com%2Fcontainernetworking%2Fcni&type=Code

some of them such important as Kubernetes.

The last tagged release is 0.7.1, however, some important improvements and bugfixes were added since the last release.

It would be nice to have a new official release so all projects that are using this library can vendor a tagged release.

xref: https://github.com/kubernetes/kubernetes/pull/91896#issuecomment-645903653

**Comment by bboreham** [comment]
Sorry about the delay; I have tagged v0.8.0.
GitHub release and release notes to follow.

**Comment by bboreham** [comment]
v0.8.0 released now.
