### ISSUE TITLE
Macvlan: Set parent interface to promiscuous mode

### ISSUE THREAD

**Issue by mario19911** [containernetworking/cni#779]
Hey,

to receive traffic on a macvlan interface it seems to be necessary that the parent  interface uses promiscuous mode.
Would it be possible to do this automatically in the CNI Plugin? I think this would be a nice feature...

**Comment by mars1024** [comment]
hey, I think kernel could help us with [dev_set_promiscuity](https://www.kernel.org/doc/htmldocs/networking/API-dev-set-promiscuity.html), so macvlan interface creation/deletion will lead parent interface' promiscuous mode to on/off.

**Comment by jellonek** [comment]
I'm almost sure that this is not yet supported by vishvananda netlink which we are using right now, so probably we should do that during the creation of sub interface using https://github.com/vishvananda/netlink/blob/master/link_linux.go#L110 - on host device. Seems trivial.

**Comment by dcbw** [comment]
@mario19911 I believe kernel drivers are supposed to set the device to promiscuous mode for you when more than the allowed number of unicast MAC addresses has been added to the driver's MAC filter. What device is the parent of your macvlan?

**Comment by squeed** [comment]
Also, this should be in the plugins repository; I'm going to close this issue - please reopen.
