### ISSUE TITLE
Promote spec to beta

### ISSUE THREAD

**Issue by sftim** [containernetworking/cni#786]
At the moment, the release status of the CNI _specification_ is unclear (see discussion about removing the existing alpha warning for  Kubernetes [documentation](https://github.com/kubernetes/website/pull/24026#issuecomment-701431015) and for the [kubelet](https://github.com/kubernetes/kubernetes/pull/94508)).

https://github.com/containernetworking/cni/blob/master/SPEC.md#version lists the version, at the time of writing, as 0.4.0, which suggests the possibility of breaking changes between now and a future stable release.

I recommend officially bumping the specification to beta and announcing that bump.

**Comment by sftim** [comment]
Motivation / background, as I see it:
- people are a _lot_ more comfortable using things labelled beta
- some firms have a policy of not using Kubernetes alpha APIs, though how they get their Pods to talk to anything I don't know
- CRI is taking a similar approach; see https://docs.google.com/document/d/1xMfiVUX4lF0G6Y_yQ4l-5-wrOneeJWcXY2NGVGuTdH8/

BTW, happy to move this discussion to an issue in the CNI repo.

**Comment by sftim** [comment]
Slightly related to https://github.com/containernetworking/cni/pull/783 and https://github.com/containernetworking/cni/issues/771

**Comment by bboreham** [comment]
>  the possibility of breaking changes between now and a future stable release.

#771 lists breaking changes we intend to make before 1.0.

> BTW, happy to move this discussion to an issue in the CNI repo.

This is an issue in the CNI repo; please explain.

**Comment by sftim** [comment]
> BTW, happy to move this discussion to an issue in the CNI repo.

D'oh.

**Comment by dcbw** [comment]
We have released 1.0 and it is no longer beta.
