### ISSUE TITLE
Plugins missing CNI tool

### ISSUE THREAD

**Issue by cyrus-mc** [containernetworking/cni#788]
Prior to 0.7.0 there were two releases (one through this repository and the other through the plugins).

This release contained two binaries, noop and cnitool. The plugins release does not contain these binaries. Are they needed for a functioning system? Recently updated our image to the latest CNI plugins (0.8.6) and finding that container networking is broken. 

Only difference I can see so far is the lack of the cnitool binary.

Node is being used as part of EKS cluster with AWS VPN CNI plugin.

**Comment by bboreham** [comment]
https://github.com/containernetworking/cni#where-are-the-binaries

**Comment by cyrus-mc** [comment]
Not related to my issue. Closing.
