### ISSUE TITLE
probes failing to connect from kubectl

### ISSUE THREAD

**Issue by hetpats** [containernetworking/cni#792]
We have 1.17 cluster running on 1.7.3 and we are having issues having both readiness and liveness are failing, we do have proper inbound and outbounds ports open , We confirmed the connection is open by telnet from host to the pod ip/port. 
Are we missing something?

**Comment by bboreham** [comment]
This repo contains a specification and some helper code for parsing messages under that specification. It is not directly involved in whatever happened in your cluster. 

Also, CNI is independent of any particular container orchestrator, so I suggest you find a Kubernetes help channel (or commercial support) to ask your question.
