### ISSUE TITLE
Consider changing CI from Travis

### ISSUE THREAD

**Issue by bboreham** [containernetworking/cni#798]
Travis is [migrating projects](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) with [finite credits](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), and we don't have any sponsorship to get more credits.

We should be able to use [provision from the CNCF](https://github.com/cncf/servicedesk#how-can-i-use-the-computing-infrastructure-by-cncf)

Related: https://github.com/containernetworking/plugins/issues/554

**Comment by antoninbas** [comment]
Looks like this was addressed in https://github.com/containernetworking/cni/pull/810 and the issue can be closed?
