### ISSUE TITLE
How to route a CNI bridge to the Internet ? 

### ISSUE THREAD

**Issue by h4n0sh1** [containernetworking/cni#812]
Hi, 

I would like to set up a default gateway to the internet for my cni bridge, can this be achieved with the ipam plugin set to "host-local" or do i need to switch to an L2 type of configuration. 

The physical gateway for my machine is a simple NIC : 
eth0 192.168.30.107/24

My current bridge conf looks something like this : 

```
{
  "cniVersion": "0.3.1",
  "name": "mynet",
  "type": "bridge",
  "bridge": "cni0",
  "isGateway": true,
  "ipMasq": true,
  "ipam": {
    "type": "host-local",
    "subnet": "10.22.0.0/16",
    "routes": [
      { "dst": "0.0.0.0/0" }
    ]
  }
}
```

My goal is to achieve a successful ping with this interface :  

`ping -I cni0 8.8.8.8`

I couldn't find in the documentation any clear and unambiguous way to set this up (egress to the internet), could somebody light my lantern ?

**Comment by bboreham** [comment]
Do you have IP forwarding turned on?
Do you have any firewall or other iptables rules which could be blocking that traffic?

**Comment by h4n0sh1** [comment]
> Do you have IP forwarding turned on?
> Do you have any firewall or other iptables rules which could be blocking that traffic?

Yes i do have ip forwarding enabled 

As for my ip table rules, there are only the default ones imported by docker : 

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

**Comment by bboreham** [comment]
Please can you do that again as `sudo iptables-save`, which dumps all the rules in a format I find easier to follow.

I suspect the `policy DROP` means you will need specific rules to enable forwarding for your CNI bridge.
The ['firewall' plugin](https://www.cni.dev/plugins/meta/firewall/) is one way to achieve that.

**Comment by h4n0sh1** [comment]
So just to make sure that this is not NAT related, i've completely wiped my ip tables and uninstalled docker, then rebooted. 

I'm still struggling to understand how i can tweak the CNI plugin to ping the internet, i've tried a different approach where i'd create my own unix bridge (that works) but then i run into an other issue : the ipam plugin will actually override the IP and configuration of that working bridge, thus preventing it from reaching the internet again. 

On top of that, when working with LXC containers or KVM machines, i generally have no issue attaching their respective tap interface to whatever bridge i want, but here whenever i try to hack the vethpair to attach to my bridge, this won't actually give connectivity to the underlying container. 

Do you know of a simple configuration template maybe that allows outgoing internet traffic for such a bridge plugin, or any solution really that would allow my containers to reach the internet using CNI ?

**Comment by bboreham** [comment]
Closing as requested information not provided.
