### ISSUE TITLE
Provide a vendor directory to avoid downloading all go modules when execute "go build"

### ISSUE THREAD

**Issue by Mingli-Yu** [containernetworking/cni#816]
After fetch the cni code via "git clone git://github.com/containernetworking/cni.git" and then continue to build the code via "go build", but it still try to fetch the dependencies defined in ../cni/go.module after  https://github.com/containernetworking/cni/commit/a7cceb916de6678dc8ab66982f791401ae1b10cb included in go 1.15. It's better to provide a vendor directory to avoid downloading all go modules when execute "go build".
go version: 1.15
cni version: v0.8.0

**Comment by antoninbas** [comment]
I'm no expert but projects that use Go modules typically no longer include a vendor directory. So I'm not sure it is "better to provide a vendor directory". See the "End of Vendoring" in https://research.swtch.com/vgo-module. The community seems to be transitioning to self-hosted or public proxies such as https://github.com/gomods/athens to ensure availability of dependencies or enable "offline" builds. You may also build your own vendor directory, with the caveat that vendor diectories are ignored by `go build` by default unless you provide `-mod vendor`.

**Comment by Mingli-Yu** [comment]
@antoninbas, thanks your response, so how to enable offline build now?

**Comment by bboreham** [comment]
Please explain what you built using `go build`.  This repo is primarily a library.

**Comment by Mingli-Yu** [comment]
@bboreham 
Yes, I indeed know the cni is a library and there is another package depends on cni in my build environment, so I need to run build against cni and want to do a offline build in my env. Thanks!

**Comment by bboreham** [comment]
Ok so the vendor directory would be in your project not in ours.

**Comment by Mingli-Yu** [comment]
@bboreham,
Thanks your response, but I don't understand what you mean. Initially I open the issue is because I clone the cni code via "git clone git://github.com/containernetworking/cni.git" and then continue to run "go build", but don't want it connect the network to fetch the dependencies defined in go.mod file for cni during "go build" phase, is there any means? Thanks in advance!

**Comment by bboreham** [comment]
>  I clone the cni code via "git clone git://github.com/containernetworking/cni.git" and then continue to run "go build"

If I do this it says "no Go files in /home/vagrant/src/github.com/containernetworking/cni".

What you indicated before is that you are building your own project, which will say something like `import "github.com/containernetworking/cni/pkg/types/current"`.  And you can have a `vendor` directory in that project.

As described at https://golang.org/ref/mod#vendoring, "the go command ignores vendor directories in locations other than the main module's root directory", so even if we did what you asked it would not change anything.  The "main module" is whatever you are building; the CNI library is not your main module.

**Comment by Mingli-Yu** [comment]
1, mkdir -p $GOPATH/src/github.com/containernetworking
2, cd $GOPATH/src/github.com/containernetworking
3, git clone git://github.com/containernetworking/cni.git
4, cd cni/libcni
5, go build

**Comment by bboreham** [comment]
This is not something you need to do, or should do.
Just import the package(s) and build your project in its directory; Go will compile all dependencies.

**Comment by Mingli-Yu** [comment]
@bboreham,
Thanks very much for your response!
Actually I don't quite understand what you mean when you say "This is not something you need to do, or should do." 

In my env, it's easy to reproduce that needs to connect the network during "go build" stage with follow steps. And all I want just provide a method not let it connect the network during "go build" stage. Thanks a lot!
1, mkdir -p $GOPATH/src/github.com/containernetworking
2, cd $GOPATH/src/github.com/containernetworking
3, git clone git://github.com/containernetworking/cni.git
4, cd cni/libcni
5, go build
