### ISSUE TITLE
Specify how a plugin is invoked

### ISSUE THREAD

**Issue by passcod** [containernetworking/cni#820]
I feel especially silly asking this as I'm assuming that... this is either obvious somehow or documented somewhere I haven't looked, but: nowhere in the spec is it established how exactly a plugin is invoked???

Reading the source (!) it seems that:

- a plugin is called with data provided via environment variables and STDIN
- env is the operation as the key (e.g. `ADD`) and the config described under each operation as the "parameters" as the value, except for the network configuration maybe?, in JSON
- STDIN is the network configuration, in JSON
- STDOUT must be JSON and is the result
- STDERR is informational messages (I assume logs) and is copied to the STDERR of the caller
- the return codes are specified in the spec (0 = success, 1-99 well-known, 100+ presumably left available to the plugin's prerogative)

If that's not already defined somewhere it would be great to have that not only as part of the spec but also the data provided as the env/stdin section fleshed out in plain. And if it _is_ defined somewhere, it should be linked from the spec I think!

**Comment by bboreham** [comment]
Did you find it?  Would you like to suggest a change that would have made it easier for you to find the info?

**Comment by passcod** [comment]
Yeah, I had the v0.4.0 tag open, not the spec-0.4.0 tag. But also, in the current version of the spec, it's right at the bottom of the Parameters section and not separately sectioned (so it doesn't appear in the ToC). If it was pulled to the top and given its own section that would help.

**Comment by bboreham** [comment]
Please take a look at #805 which re-orders lots of things.
Comment there if you have suggestions, thanks!

**Comment by passcod** [comment]
Oh that's perfect!
