### ISSUE TITLE
"Can't Load Package" Error

### ISSUE THREAD

**Issue by brianmoore180** [containernetworking/cni#829]
I'm new to go, so this might be a user issue. I tried following the cnitool instructions. It said to run:
`go get github.com/containernetworking/cni`

However, I get this error: can't load package: package github.com/containernetworking/cni: no Go files in /home/myusername/go/src/github.com/containernetworking/cni

I tried continuing with the next instructions but ran into issues with it not finding packages.

plugins/meta/bandwidth/ifb_creator.go:22:2: cannot find package "github.com/containernetworking/plugins/pkg/ip" in any of:
        /usr/lib/go-1.10/src/github.com/containernetworking/plugins/pkg/ip (from $GOROOT)
        /home/myusername/go/src/github.com/containernetworking/plugins/pkg/ip (from $GOPATH)

**Comment by bboreham** [comment]
What version of Go are you using?
It seems to work for me with `go1.15.6`:

```
$ go get github.com/containernetworking/cni
go: github.com/containernetworking/cni upgrade => v0.8.1
go: downloading github.com/containernetworking/cni v0.8.1
$ go install github.com/containernetworking/cni/cnitool
```

The `go get` line is unnecessary now so the instructions should be updated.
