### ISSUE TITLE
portmap meta plugin exposes port to the whole Internet without any restriction using firewalld

### ISSUE THREAD

**Issue by waulee** [containernetworking/cni#830]
Currently I investigated a security issue of the CNI portmap plugin. (my host got banned becase of on container udp port that I unintentionally exposet to the whole Internet) 
CNI conflist piece (on my Fedora 32):

{
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "firewall"
    },
PREROUTING iptables/nftables rules generated by above config running a "podman run -ti -p 8080:8080/tcp alpine ash" exposes the 8080 tcp port to the whole internet. (any port actually) 
I use zones in Firewalld to keep my port filterred and virtual hosts firewalled from outside, alhtough my zones got not evaluated becase DNAT portmap rules got installed after the zone matching rules, and with source 0.0.0.0/0 (the whole internet).

Currently I use the following config feature of portmap to mitigate the unwanted exposure:

{
      "type": "portmap",
      "capabilities": {"portMappings": true},
      "conditionsV4": ["-m", "set", "--match-set", "work", "src"]
    },
I set up manually my "work" ipset totally redundant from the my zone in Firewalld.

My sugestion follows:
I would be nice to have a portmap config parameter to instrunct portmap plugin to install the DNAT rules to the pre-configured zone of the Firewalld. like: 
"firewalld-zone": "work"
resulting:
firewall-cmd --zone=work  --add-forward-port=port=8080:proto=tcp:toport=8080:toaddr=<container IP>

"iptables-custom-chain": "some-user-predefined-chain"
equivalent for iptables, or it could be the same config parameter.

The firewall plugin zone parameter only sets the source and SNAT for the container IP.

**Comment by marc-o94** [comment]
Hey i encountered the same issue on Rhel 8.3 using cni with podman. All exposed ports are not covered by the firewalld rules. Took me hours to identify cni as the source of the problem.

@waulee could you please be more specific how you worked around this issue?

**Comment by dcbw** [comment]
@waulee could you attach the output of `iptables-save` when things don't work like you expect?

**Comment by bboreham** [comment]
Please note the plugins such as portmap were split out from this repo some years ago; could you please re-raise there?
https://github.com/containernetworking/plugins/issues

**Comment by waulee** [comment]
Thansk @bboreham! I openned one there, so this can be closed.

https://github.com/containernetworking/plugins/issues/618
