### ISSUE TITLE
IP of pod stuck in Terminating assigned to a new pod - CNI

### ISSUE THREAD

**Issue by asafsofer-sl** [containernetworking/cni#837]
Please advice what is the CNI approach for pod in Terminating status , does all the resources attached to it are being released and can be reused (even if the pod in Terminating status for a long time , and not being deleted) ?
in my case i can see the pod is in status Terminating  and other pod got assigned with the same IP, how to avoid such outcome ?

**Comment by mars1024** [comment]
Could  you help to append more details, eg. kubernetes versions, CNI config and pod yamls...

**Comment by asafsofer-sl** [comment]
Hello,

the k8s version is :  1.17.9 
In Known issue with that version ?
Also i found out this article talking on same problem : 

https://github.com/aws/amazon-vpc-cni-k8s/issues/1091

**Comment by mars1024** [comment]
I see the issue you mentioned above has been closed by a bug fix.
And IMO, I don't think `host-local` (formal ipam plugin maintained by CNI) will cause IP duplication. Because it is using a file lock for each IP and releasing the lock is almost the last action of terminating a pod by kubelet.

**Comment by asafsofer-sl** [comment]
Hello Mars , 

In which CNI plugin release it was fixed ? which version , might be i am working with old version.

**Comment by asafsofer-sl** [comment]
Here is the net.d file, it was fix after : "cniVersion":"0.3.0" ?

File name = 10-azure.conflist 
 
{
   "cniVersion":"0.3.0",
   "name":"azure",
   "plugins":[
      {
         "type":"azure-vnet",
         "mode":"transparent",
         "ipsToRouteViaHost":["169.254.20.10"],
         "ipam":{
            "type":"azure-vnet-ipam"
         }
      },
      {
         "type":"portmap",
         "capabilities":{
            "portMappings":true
         },
         "snat":true
      }
   ]
}

**Comment by squeed** [comment]
This is a question for the kubelet - when does a Terminating pod have its underlying PodSandbox address released? In any case, it's not a CNI question.
