### ISSUE TITLE
v1.0.0 tag confusion

### ISSUE THREAD

**Issue by AlekSi** [containernetworking/cni#856]
[Tag v1.0.0 is there](https://github.com/containernetworking/cni/releases/tag/v1.0.0), so the Go module for that version is [available](https://pkg.go.dev/github.com/containernetworking/cni), and dependabot prompts us to update, but:
* there is not [release](https://github.com/containernetworking/cni/releases) for that version;
* the [milestone for v1.0.0](https://github.com/containernetworking/cni/milestone/1) is open and contains open issues;
* [roadmap](https://github.com/containernetworking/cni/blob/master/ROADMAP.md) wasn't updated.

What version of the Go module do you recommend using?

**Comment by squeed** [comment]
Very good point. We didn't quite get the time to do all of the bookeeping for 1.0, but I'll create the github release now.
