### ISSUE TITLE
Multus link goes to empty repository

### ISSUE THREAD

**Issue by kpaschen** [containernetworking/cni#867]
The Readme currently points here: https://github.com/Intel-Corp/multus-cni for multus, but that repository is empty (and the readme says "takeover by codermak", on top of that). I think the right link for Multus would be this: https://github.com/k8snetworkplumbingwg/multus-cni .

**Comment by mars1024** [comment]
Do you mind fixing this through a PR? Thanks!

**Comment by kpaschen** [comment]
> Do you mind fixing this through a PR? Thanks!

https://github.com/containernetworking/cni/pull/868

**Comment by dcbw** [comment]
Solved by #868
