### ISSUE TITLE
spec: plugin shouldn't care if it has been wrapped

### ISSUE THREAD

**Issue by eyakubovich** [containernetworking/cni#87]
Currently the CNI works best if there are two levels of plugins: main and ipam.
Fewer levels (i.e. just main plugin) works fine but more levels are a bit problematic. Consider how the ipam plugin finds its configuration. The JSON that it receives is the same one that was fed to the main plugin. E.g.

```
{
    "name": "foo",
    "type": "bridge",
    "ipam": {
        "type": "host-local",
        "subnet": "10.1.2.0/24"
    }
}
```

The `host-local` IPAM plugin looks for its config under the `ipam` key. It will also look for the network name under the `name` key. But what happens if we wanted to have 3 layers? For example, what if we wanted to add another plugin that will install firewall rules to make sure the network can't cross talk to another network:

```
{
    "name": "foo",
    "type": "isolator",
    "deny": [ "10.0.0.0/8" ],
    "net": {
        "type": "bridge",
        "ipam": {
            "type": "host-local",
            "subnet": "10.1.2.0/24"
        }
    }
}
```

(If this is actually a config file that a user enters, the UX is horrible but we'll ignore it for now).

The problem with this approach is that both `bridge` and `host-local` plugins now need to look for their configs in a slightly different place (`net` and `net.ipam`, respectively). There's of course nothing to tell them that. The network name is still at `name` key.

How should we handle this? One approach is to have the invoking plugin feed only the JSON that is specific for the plugin. For example, an ipam plugin would just receive:

```
{
    "type": "host-local",
    "subnet": "10.1.2.0/24"
}
```

The network name would then be passed via an environment variable: `CNI_NETNAME`. I think this approach would work well but the nested JSON does not present the best UX, in the cases where these configs are entered by the user and stored on disk. Ideas for better handling UX are welcomed.

**Comment by bboreham** [comment]
Can this be closed now we have chaining?

**Comment by squeed** [comment]
Yup.

**Comment by rosenhouse** [comment]
Ok then, closing :haircut_man:
