### ISSUE TITLE
Proposal: improved routing

### ISSUE THREAD

**Issue by oskarirauta** [containernetworking/cni#870]
My problem is that my host system (OpenWrt) cannot reach container(s)/pod(s) properly and eventually I was able to fix this by changing the route.. route coming from cni is:

`
10.129.0.0/24 dev cni-podman0 proto kernel scope link src 10.129.0.1
`

I can fix this with following:

```
ip route del 10.129.0.0/24
ip route add 10.129.0.0/24 dev cni-podman0 proto kernel scope link via 10.129.0.1 src $LAN_IP
```

10.129.0.0/24 is my cni network subnet, and gw is 10.129.0.1

so I am wondering if we could have optional fields to route with via and src - netlink go module used already does support it.

**Comment by oskarirauta** [comment]
So, would it be possible to add src and via to types.go route?

**Comment by matthewdupre** [comment]
@oskarirauta which plugin(s) are you trying to use?  Each plugin makes different choices about how to reach containers.

**Comment by oskarirauta** [comment]
`{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-podman0",
      "isGateway": true,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "routes": [{ "dst": "0.0.0.0/0" }],
        "ranges": [
          [
            {
              "subnet": "10.129.0.0/24",
              "gateway": "10.129.0.1"
            }
          ]
        ]
      }
    },
    {
      "type": "portmap",
      "snat": false,
      "capabilities": {
        "portMappings": false
      }
    },
    {
      "type": "firewall",
      "backend": "iptables"
    },
    {
      "type": "tuning"
    }
  ]
}`

It would seem that I am using bridge plugin. Routes are on ipam part.

Adding options such as via or src, is useless, since when file is readed and routes part is extracted, it doesn't use netlink module's route structure, instead it uses cni's [types.go](https://github.com/containernetworking/cni/blob/master/pkg/types/types.go) structure which only allows Dst and GW.

**Comment by mccv1r0** [comment]
Linux should magically use 10.129.0.1 as the src IP any time Linux tries to connect to anything with a destination on the 10.129.0.0/24 subnet.

**Comment by oskarirauta** [comment]
Sure, but src should be lan_ip which is 10.0.0.x/9.... so I would need it to go via 10.129.0.1 but with src of host machine ip on lan...

**Comment by oskarirauta** [comment]
Problem was with firewalling on host. Issue closed.
