### ISSUE TITLE
when use crictl to start a pod-->checking pod default_nginx-sandbox for CNI network "my-macvlan": invalid version "": the version is empty

### ISSUE THREAD

**Issue by xuegege5290** [containernetworking/cni#882]
[root@LIN-DFF2F8FE6FC ~]# crictl images
IMAGE TAG IMAGE ID SIZE
127.0.0.1:5000/alpine latest 008f284ae2316 7.43MB
127.0.0.1:5000/busybox latest af2f74c517aac 1.42MB
127.0.0.1:5000/centos latest 5d0da3dc97646 239MB
127.0.0.1:5000/pause latest da86e6ba6ca19 747kB
k8s.gcr.io/pause 3.1 da86e6ba6ca19 747kB
k8s.gcr.io/pause 3.6 da86e6ba6ca19 747kB

[root@LIN-DFF2F8FE6FC ~]# cat sandbox-config.json
{
"metadata": {
"name": "nginx-sandbox",
"namespace": "default",
"attempt": 1,
"uid": "hdishd83djaidwnduwk28bcsb"
},
"linux": {
}
}

[root@LIN-DFF2F8FE6FC ~]# crictl runp sandbox-config.json
FATA[0000] run pod sandbox: rpc error: code = Unknown desc = failed to get network status for pod sandbox k8s_nginx-sandbox_default_hdishd83djaidwnduwk28bcsb_1(4de20b37e350a6ad4842dd280891a72fccfe7556aca7878f12352d56a72f7153): error checking pod default_nginx-sandbox for CNI network "my-macvlan": invalid version "": the version is empty

**Comment by xuegege5290** [comment]
@lstoll @krobertson @danp

**Comment by mars1024** [comment]
What CNI network configuration is being used?

**Comment by MikeZappa87** [comment]
> [root@LIN-DFF2F8FE6FC ~]# crictl images IMAGE TAG IMAGE ID SIZE 127.0.0.1:5000/alpine latest 008f284ae2316 7.43MB 127.0.0.1:5000/busybox latest af2f74c517aac 1.42MB 127.0.0.1:5000/centos latest 5d0da3dc97646 239MB 127.0.0.1:5000/pause latest da86e6ba6ca19 747kB k8s.gcr.io/pause 3.1 da86e6ba6ca19 747kB k8s.gcr.io/pause 3.6 da86e6ba6ca19 747kB
> 
> [root@LIN-DFF2F8FE6FC ~]# cat sandbox-config.json { "metadata": { "name": "nginx-sandbox", "namespace": "default", "attempt": 1, "uid": "hdishd83djaidwnduwk28bcsb" }, "linux": { } }
> 
> [root@LIN-DFF2F8FE6FC ~]# crictl runp sandbox-config.json FATA[0000] run pod sandbox: rpc error: code = Unknown desc = failed to get network status for pod sandbox k8s_nginx-sandbox_default_hdishd83djaidwnduwk28bcsb_1(4de20b37e350a6ad4842dd280891a72fccfe7556aca7878f12352d56a72f7153): error checking pod default_nginx-sandbox for CNI network "my-macvlan": invalid version "": the version is empty

Are you able to supply your network configuration?

**Comment by xuegege5290** [comment]
already finished before!thanks a lot.

**Comment by xuegege5290** [comment]
> What CNI network configuration is being used?

Because the configration,i already solve the problem.Thanks for mention the idea.I close the question.
