### ISSUE TITLE
spec: UPDATE/CHANGE action

### ISSUE THREAD

**Issue by dcbw** [containernetworking/cni#89]
If details of the network change while the pod is alive there needs to be some way to run the CNI plugin to potentially update the pod's network setup for those changes.  To be clear, this would be for an existing network that changes some metadata or internal implementation details that the CNI plugin could determine and act upon.  For example, in our simple OpenShift multitenant plugin, the network's VNID can change based on administrator action and we need to run the pod network config plugin to updates some pod-specific rules on our OVS vswitch.

Since CNI plugins are executables/scripts that only run on ADD/DEL and quit after their work is done, they have no mechanism for watching for network/config changes.  The container runtime (the thing calling ADD/DEL) is the most likely candidate for the UPDATE request, based on internal information it gets from somewhere (a plugin of its own, or other events).

I wouldn't consider this a full ADD/DEL because the network object itself isn't changing, just some arbitrary/internal attributes of the network object.  Second, ADD/DEL would obviously interrupt connectivity and might change the IP address of the pod during its lifetime which is undesirable.

Thoughts?

**Comment by dcbw** [comment]
A naive implementation would be the same as the ADD call (since I think all of the parameters for ADD are relevant for UPDATE/CHANGE) and the response would probably the same too, since depending on the implementation there might be IPAM changes.  But I think it would confusing to re-use ADD, unless a new parameter was added to indicate the ADD was actually a change request.

**Comment by bprashanth** [comment]
I think it should perform periodic reconciliation by treating input json as the source of truth and applying any changes. If there are no changes, just return the current values (eg: bridge+hostipam would simply return podip -- this is different from ADD where hostipam would allocate a new pod ip). 

This is starting to sound like Sync (status + update). Though I know at one point we discussed status I can't remember why it was deemed unnecessary.

**Comment by steveeJ** [comment]
This sounds reasonable to me, and the only thing I can think of why we don't have it is because it makes _DEL_ more complicated if the state was mutated since _ADD_. @dcbw are you going to propose a spec and implementation change?

**Comment by steveeJ** [comment]
Ping @dcbw

**Comment by steveeJ** [comment]
@rosenhouse @dcbw is one of you willing to start a design document (e.g. on Google Docs) that we use to collect use-cases and their requirements? Having concrete examples will be of great help to decide on and possibly design this feature.

**Comment by rosenhouse** [comment]
@steveeJ this is timely.  We're beginning to work our our the higher-level UX requirements for container networking on cloudfoundry, and applying dynamic policy changes via some kind of UPDATE or idempotent ADD seems natural.  I should have more to share on use-cases and requirements late next week.

cc: @evanfarrar

**Comment by rosenhouse** [comment]
As requested, [here is a document to collect use-cases](https://docs.google.com/document/d/1HqkEIsJV9ZqTCygo6TK9OKZzEZSPhfDPkmnqshtWAKI/edit) for dynamic configuration (e.g. UPDATE / UPSERT)

**Comment by feiskyer** [comment]
@dcbw Is this still on the scheduler? UPDATE action could help for kubernetes `updateRuntimeConfig` with CIDR changes.
