### ISSUE TITLE
Cni spec Question: Why do we need to place config file in /etc/cni/net.d?

### ISSUE THREAD

**Issue by yash97** [containernetworking/cni#892]
Why cni config file is not some CRD object that container runtime can pull from K8s and execute binaries.

Thank You.

**Comment by MikeZappa87** [comment]
> Why cni config file is not some CRD object that container runtime can pull from K8s and execute binaries.
> 
> Thank You.

The CNI is not executed by K8s, it is executed by the container runtime (containerd, cri-o). These paths are configurable as well and /etc/cni/net.d is the default. Its worth noting the CNI is not specific to Kubernetes as well.
