### ISSUE TITLE
converting plugin result to wrong config version results in regression 

### ISSUE THREAD

**Issue by mikebrow** [containernetworking/cni#895]
https://github.com/weaveworks/weave/issues/3936
https://github.com/containerd/containerd/issues/6921

@fuweid drafted a prototype fix:
https://github.com/fuweid/containerd/commit/8c5607ca4edae3bfd21a15f7d3f9db2d17fee0f0

@squeed @MikeZappa87

**Comment by fuweid** [comment]
@squeed For sure. I will file the pr! Thanks!

**Comment by mikebrow** [comment]
nod.. puts us in a bind will need both cni lib and weave to fix.. weave fix so we can work fine from containerd 1.6.0-1.6.4 and here in cni so 1.6.5 can work with the version of weave that does not reply with config version in the result..

**Comment by squeed** [comment]
@mikebrow Shouldn't this work around Weave without them needing to fix their buggy behavior?

**Comment by squeed** [comment]
oh nevermind, I just parsed what you said. I'll see if I can bug anyone at weave.

**Comment by mikebrow** [comment]
yes it will.. and we'll put it in our r.next service stream right away after test and cni release tag and contained/go-cni brings in the new cni and containerd/containerd brings in the new go-cni and cherry pick to service for 1.6.5 ... 
Sigh :-)

**Comment by mikebrow** [comment]
@mrunalp heads up another spin on cni lib coming to resolve weave issue with containerd and cri-o cheers..

**Comment by hswong3i** [comment]
Doesn't https://github.com/weaveworks/weave/pull/3939 solve this issue?

**Comment by dcbw** [comment]
This is valid. But https://github.com/fuweid/containerd/commit/8c5607ca4edae3bfd21a15f7d3f9db2d17fee0f0 is not quite right.

**Comment by fuweid** [comment]
> can the behavior be to back-fill the result version to the config iff the result doesn't have a version specified?

Yes.

> While it's helpful to have libcni do this, it encourages plugins to be lazy and not conform to the spec's requirement of setting the Result CNIVersion correctly.



The spec said that the cniVersion of result is the same version supplied on input https://github.com/containernetworking/cni/blob/main/SPEC.md#L480.
Based on that, I applied to request version to override the result, just in case that the plugin returns the wrong version. 

Maybe out of topic. Is it possible to remove the version in result? The request always said what version it wants...
