### ISSUE TITLE
[Feature] Adding an interface to a running Pod

### ISSUE THREAD

**Issue by tlehman** [containernetworking/cni#912]
I am working on adding SR-IOV functionality to the Harvester kubernetes product. I wrote this [user story](https://github.com/tlehman/harvester/blob/sriov-hep/enhancements/20220614-single-root-io-virtualization.md#story-1) (with cool mermaid diagrams) to explain what I am trying to do. The sequence diagram shows that in order for a pod to request a VF from the host node, the running pod has to be re-created.

Using Multus CNI, when a Pod is created, the CNI configuration creates the interfaces for the Pod. This is the `AddedInterface` event I see when I `kubectl describe` the Pod.

If I wanted to modify CNI to support an `AddedInterface` event on a running Pod, where would I start?

**Comment by dcbw** [comment]
@tlehman CNI actually doesn't deal with pods at all, it just deals with interfaces in the sandbox. It's actually Kubernetes that has a policy of not dynamically adding/removing interfaces from/to a pod at runtime. CNI doesn't care about that, you can ADD/DEL new interfaces to a sandbox all day while it's running.

So your question is more for Kubernetes and Multus; but it's really Kube that has the limitation/policy.
