### ISSUE TITLE
The term "master" needs to change to "main" in several files

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containernetworking/cni#946]
There are several instances of the word "master" in 10 files in this project that should be changed to "main".  Some instances in README.md can transition now, while others can not, as they're pointers to other projects that have not yet transitioned.  However, most, if not all, of the remaining nine files, including CODE-OF-CONDUCT.md, CONVENTIONS.md, RELEASING.md, and others can and should be changed now.

I searched only for "master", the words "slave", "blacklist", and "whitelist" should also be searched for and converted ifpossible.

**Comment by squeed** [comment]
Hey, thanks for pointing this out. You're right that some of our dependencies use these outdated terms, and it will be quite some time (argh) before Linux gets with the program.

I'll try and pick this up for v1.2. Do you have time to work on any of this?

**Comment by TomSweeneyRedHat** [comment]
I'll try to get to it this weekend.

**Comment by squeed** [comment]
Great.

The biggest source of the term "master" in the repository is likely the notion of a sub-interface, e.g. a bridge or vlan. AIUI the community has not picked a new term for this. I'd love to be wrong.

**Comment by TomSweeneyRedHat** [comment]
Yeah, that one can't be changed yet.  Two years in, and they're still haggling about the appropriate term, from what I understand.

**Comment by squeed** [comment]
Filed https://github.com/containernetworking/cni/pull/1045 to clean this one up.
