### ISSUE TITLE
Add AWS instance type 'C6in' support

### ISSUE THREAD

**Issue by ten-jed** [containernetworking/cni#947]
Add AWS instance type 'C6in' support

**Comment by divaspathak** [comment]
I want to work on this issue. Can you please assign it to me?

**Comment by squeed** [comment]
I suspect you have the wrong repository; this is for the CNI spec and has nothing AWS specific. Perhaps you mean https://github.com/aws/amazon-vpc-cni-k8s ?

I'm closing this; please reopen if needed.
