### ISSUE TITLE
Question: Configuration of IPAM

### ISSUE THREAD

**Issue by zachgersh** [containernetworking/cni#95]
Hey All,

Great work going on here, much appreciated (not said enough):

Wanted to ask - why an inline struct was defined here and not a type?

https://github.com/appc/cni/blob/master/pkg/types/types.go#L61

We're integration this into a project and want to be able to configure the IPAM (using your type) upfront. Would you mind if I PR'ed this into being a concrete type or was there a specific design reason for it being as shown above?

Cheers!

**Comment by jonboulle** [comment]
I can't think of a good reason so I'd definitely be amenable to such a PR

**Comment by zachgersh** [comment]
@jonboulle great - I'll get that done sometimes this weekend and send that over.
